/**
 * Bayer ordered dithering — 1-bit rendering of continuous scalar fields.
 *
 * The whole utility is three lines of arithmetic per pixel:
 *
 *   const v = fn(x / (w - 1), y / (h - 1), t);   // any 0..1 field
 *   const threshold = (BAYER_8[y % 8][x % 8] + 0.5) / 64;
 *   pixels[i] = v > threshold ? ink : paper;     // 1-bit output
 *
 * Everything else here exists to make that fast, correct and reusable.
 *
 * WHY ORDERED AND NOT ERROR-DIFFUSION: Floyd-Steinberg produces a finer,
 * more "photographic" result, but its output is serial (each pixel's error
 * feeds its neighbours) so it cannot be evaluated per-pixel, it dissolves
 * into visual noise rather than reading as a deliberate texture, and it
 * shimmers incoherently when animated. A Bayer matrix is a fixed threshold
 * map: stateless, order-independent, and — the point of the whole exercise —
 * it produces a *visible repeating cell structure* that reads as print
 * halftone rather than as digital noise.
 *
 * SCALE IS THE DESIGN CONTROL, NOT DPR. This module deliberately renders at
 * 1 device pixel per dither cell and lets CSS upscale with
 * `image-rendering: pixelated`. Rendering at devicePixelRatio would make each
 * cell subpixel-sized on a retina display and the ordered structure would
 * collapse back into flat grey — the exact failure this technique exists to
 * avoid. `scale` is the width of one cell in CSS pixels; an 8x8 Bayer tile is
 * therefore `8 * scale` CSS px across, and that number is the texture's
 * apparent grain. scale 1 is invisible structure, 3-4 reads as halftone,
 * 8+ reads as deliberate chunky pixel art.
 *
 * COST OF RESOLUTION. Work is one flat loop over w*h with no allocation and
 * no per-pixel canvas calls, so cost is linear in cell count and the field
 * function dominates. On a 1440x900 hero the buffer is:
 *
 *   scale 1 -> 1440x900 = 1296k cells   (9x the work of scale 3)
 *   scale 2 ->  720x450 =  324k cells
 *   scale 3 ->  480x300 =  144k cells   <- good default for a full-bleed field
 *   scale 4 ->  360x225 =   81k cells
 *   scale 6 ->  240x150 =   36k cells
 *
 * Measured per frame at 144k cells (Apple silicon, Chrome), field evaluation
 * only; the buffer write and putImageData add well under 1ms on top:
 *
 *   gradientRamp   0.8ms      streakBands   5.3ms
 *   glyph SDF      1.9ms      radialBurst  15.1ms
 *   globe          4.8ms      (globe with graticule and landmass off: 1.4ms)
 *
 * So at scale 3 everything except radialBurst animates comfortably inside a
 * 30fps budget. radialBurst is the expensive one — it integrates several trace
 * layers and a turbulence field per pixel — so animate it at scale 4+ (81k
 * cells, ~8ms) or render it once and leave it static. Never animate a
 * full-bleed field at scale 1: that is 1.3M field calls per frame.
 *
 * The dials that actually cost, in order: `scale` (quadratic), then for
 * radialBurst `layers` and `warpOctaves`, and for globe `graticule`/`landmass`
 * (which together are 70% of its cost — set both to 0 for a plain shaded
 * sphere).
 *
 * Dependency-free and framework-free by design: one canvas, no WebGL context
 * to budget, no shader compile, and it degrades to a single static frame
 * under `prefers-reduced-motion`.
 */

/**
 * The 8x8 Bayer (ordered-dither) threshold matrix, values 0..63.
 *
 * NOT transcribed from memory. Generated by the recursive construction
 *
 *   M(1) = [0]
 *   M(2n) = [[4*M(n) + 0, 4*M(n) + 2],
 *            [4*M(n) + 3, 4*M(n) + 1]]
 *
 * and cross-checked against the independent bit-twiddling definition
 * (interleave the bits of `x ^ y` and `y`, then bit-reverse) — both
 * constructions agree cell for cell. Verified properties:
 *
 *   - it is an exact permutation of 0..63 (no repeats, no gaps), which is
 *     what makes the dither tonally linear: a constant field of value k/64
 *     lights exactly k pixels in every 8x8 tile, for all 65 levels;
 *   - at 50% the lit set has zero deviation from 2-of-4 in every 2x2 block,
 *     i.e. dots are maximally dispersed instead of clumping.
 *
 * The recursive construction is what guarantees dispersion: each subdivision
 * step places the four children of a cell in the order top-left, bottom-right,
 * top-right, bottom-left, so successively-added dots always land as far from
 * each other as the current scale allows.
 */
export const BAYER_8: readonly (readonly number[])[] = [
  [0, 32, 8, 40, 2, 34, 10, 42],
  [48, 16, 56, 24, 50, 18, 58, 26],
  [12, 44, 4, 36, 14, 46, 6, 38],
  [60, 28, 52, 20, 62, 30, 54, 22],
  [3, 35, 11, 43, 1, 33, 9, 41],
  [51, 19, 59, 27, 49, 17, 57, 25],
  [15, 47, 7, 39, 13, 45, 5, 37],
  [63, 31, 55, 23, 61, 29, 53, 21],
] as const;

/**
 * The same matrix pre-divided into 0..1 thresholds and flattened.
 *
 * The inner loop indexes this with `(y & 7) << 3 | (x & 7)`, which replaces a
 * nested array deref, an integer add and a divide per pixel with a single
 * Float64Array load. At 144k cells a frame that is worth having.
 */
const BAYER_8_THRESHOLDS: Float64Array = (() => {
  const out = new Float64Array(64);
  for (let y = 0; y < 8; y++) {
    for (let x = 0; x < 8; x++) {
      out[(y << 3) | x] = (BAYER_8[y]![x]! + 0.5) / 64;
    }
  }
  return out;
})();

/**
 * A scalar field. Returns coverage in 0..1 (values outside are clamped by the
 * comparison anyway: <=0 is always paper, >1 is always ink).
 *
 * @param u horizontal position, 0..1 across the buffer
 * @param v vertical position, 0..1 down the buffer
 * @param t time in seconds; static fields ignore it
 */
export type FieldFn = (u: number, v: number, t: number) => number;

export type DitherOptions = {
  /**
   * Width of one dither cell in CSS pixels. The buffer is sized
   * `ceil(cssSize / scale)`. See the module note — this is the grain control
   * and the single biggest lever on both look and cost. Default 3.
   */
  scale?: number;
  /** Colour of a lit cell (`v > threshold`). Any CSS colour. Default '#fff'. */
  ink?: string;
  /**
   * Colour of an unlit cell. Any CSS colour, including 'transparent' so the
   * field composites over whatever is behind the canvas. Default '#000'.
   */
  paper?: string;
  /** Time in seconds handed to the field function. Default 0. */
  time?: number;
  /**
   * Explicit CSS size. Defaults to the canvas's measured layout box, falling
   * back to its current width/height attributes when it is not yet laid out.
   */
  cssWidth?: number;
  cssHeight?: number;
  /** Swap ink and paper without touching the field. Default false. */
  invert?: boolean;
  /**
   * Added to the field value before thresholding, so a field can be pushed
   * lighter or darker without rewriting it. Default 0.
   */
  bias?: number;
  /**
   * Exponent applied to the field value (`v ** gamma`) before thresholding.
   * >1 darkens midtones, <1 lifts them. Default 1 (skipped entirely).
   */
  gamma?: number;
  /**
   * Set `image-rendering: pixelated` and the CSS box on the canvas so the
   * low-res buffer upscales with hard cell edges. Turn off only if the
   * caller styles the canvas itself. Default true.
   */
  applyStyles?: boolean;
};

export type DitherFrame = {
  /** Buffer dimensions in cells. */
  width: number;
  height: number;
  /** Total cells written. */
  cells: number;
  /** Fraction of cells that came out as ink, 0..1. Useful for calibration. */
  litRatio: number;
};

type CanvasCache = {
  ctx: CanvasRenderingContext2D;
  imageData: ImageData;
  /** 32-bit view over the same bytes as imageData.data. */
  pixels: Uint32Array;
  width: number;
  height: number;
};

/**
 * Per-canvas render state. A WeakMap means a canvas that is removed from the
 * DOM takes its buffer with it — no manual disposal, no leak.
 */
const caches = new WeakMap<HTMLCanvasElement, CanvasCache>();

/**
 * Uint32 pixel writes are byte-order sensitive, so the packing order has to
 * match the platform. Every browser we ship to is little-endian, but probing
 * costs one-time nothing and makes the module honest.
 */
const IS_LITTLE_ENDIAN: boolean = (() => {
  const probe = new ArrayBuffer(4);
  new Uint32Array(probe)[0] = 0x01020304;
  return new Uint8Array(probe)[0] === 0x04;
})();

function packRGBA(r: number, g: number, b: number, a: number): number {
  return IS_LITTLE_ENDIAN
    ? ((a << 24) | (b << 16) | (g << 8) | r) >>> 0
    : ((r << 24) | (g << 16) | (b << 8) | a) >>> 0;
}

const colourCache = new Map<string, number>();

/**
 * Resolve any CSS colour string to a packed pixel.
 *
 * Hex and rgb()/rgba() are parsed directly; anything else (named colours,
 * hsl(), color-mix(), var() already resolved by the caller) is normalised by
 * letting a 1x1 canvas rasterise it, which is the only dependency-free way to
 * cover the full CSS colour grammar. Results are memoised because the inner
 * loop must never touch this.
 */
function parseColour(input: string): number {
  const key = input.trim().toLowerCase();
  const hit = colourCache.get(key);
  if (hit !== undefined) return hit;

  let packed: number | undefined;

  if (key === 'transparent') {
    packed = 0;
  } else if (key.startsWith('#')) {
    const hex = key.slice(1);
    const expand = (c: string) => parseInt(c + c, 16);
    if (hex.length === 3 || hex.length === 4) {
      packed = packRGBA(
        expand(hex[0]!),
        expand(hex[1]!),
        expand(hex[2]!),
        hex.length === 4 ? expand(hex[3]!) : 255
      );
    } else if (hex.length === 6 || hex.length === 8) {
      packed = packRGBA(
        parseInt(hex.slice(0, 2), 16),
        parseInt(hex.slice(2, 4), 16),
        parseInt(hex.slice(4, 6), 16),
        hex.length === 8 ? parseInt(hex.slice(6, 8), 16) : 255
      );
    }
  } else if (key.startsWith('rgb')) {
    const nums = key
      .slice(key.indexOf('(') + 1, key.lastIndexOf(')'))
      .split(/[,\s/]+/)
      .filter(Boolean)
      .map(Number);
    if (nums.length >= 3 && nums.every((n) => !Number.isNaN(n))) {
      const alpha = nums.length > 3 ? Math.round((nums[3] ?? 1) * 255) : 255;
      packed = packRGBA(nums[0]!, nums[1]!, nums[2]!, alpha);
    }
  }

  if (packed === undefined) {
    packed = rasteriseColour(input);
  }

  colourCache.set(key, packed);
  return packed;
}

/** Last-resort colour parse: paint one pixel and read the bytes back. */
function rasteriseColour(input: string): number {
  if (typeof document === 'undefined') return packRGBA(255, 255, 255, 255);
  const probe = document.createElement('canvas');
  probe.width = 1;
  probe.height = 1;
  const ctx = probe.getContext('2d', { willReadFrequently: true });
  if (!ctx) return packRGBA(255, 255, 255, 255);
  ctx.clearRect(0, 0, 1, 1);
  ctx.fillStyle = input;
  ctx.fillRect(0, 0, 1, 1);
  const [r, g, b, a] = ctx.getImageData(0, 0, 1, 1).data;
  return packRGBA(r ?? 0, g ?? 0, b ?? 0, a ?? 255);
}

/**
 * Get (or lazily build) the reusable ImageData for a canvas at the given cell
 * dimensions. Reallocates only when the size actually changes, so steady-state
 * animation allocates nothing at all.
 */
function getCache(
  canvas: HTMLCanvasElement,
  width: number,
  height: number
): CanvasCache | null {
  const existing = caches.get(canvas);
  if (existing && existing.width === width && existing.height === height) {
    return existing;
  }

  const ctx =
    existing?.ctx ??
    canvas.getContext('2d', { alpha: true, willReadFrequently: false });
  if (!ctx) return null;

  canvas.width = width;
  canvas.height = height;

  const imageData = ctx.createImageData(width, height);
  const cache: CanvasCache = {
    ctx,
    imageData,
    pixels: new Uint32Array(imageData.data.buffer),
    width,
    height,
  };
  caches.set(canvas, cache);
  return cache;
}

/**
 * Render one 1-bit frame of `fn` into `canvas`.
 *
 * Writes every cell through a single reused ImageData via a Uint32Array view
 * and blits once with putImageData. There is deliberately no fillRect
 * anywhere: a per-cell fillRect on a 144k-cell buffer is ~144k canvas state
 * transitions and lands in the tens-of-milliseconds range, versus roughly 1ms
 * for the typed-array write.
 */
export function ditherToCanvas(
  canvas: HTMLCanvasElement,
  fn: FieldFn,
  opts: DitherOptions = {}
): DitherFrame {
  const {
    scale = 3,
    ink = '#ffffff',
    paper = '#000000',
    time = 0,
    invert = false,
    bias = 0,
    gamma = 1,
    applyStyles = true,
  } = opts;

  const cellSize = Math.max(1, scale);

  // Measured layout box, falling back to the attribute size before first
  // layout. getBoundingClientRect is the only DOM read in the hot path and it
  // happens once per frame, not once per cell.
  let cssWidth = opts.cssWidth;
  let cssHeight = opts.cssHeight;
  if (cssWidth === undefined || cssHeight === undefined) {
    const rect = canvas.getBoundingClientRect();
    cssWidth = cssWidth ?? (rect.width || canvas.width || 1);
    cssHeight = cssHeight ?? (rect.height || canvas.height || 1);
  }

  const width = Math.max(1, Math.ceil(cssWidth / cellSize));
  const height = Math.max(1, Math.ceil(cssHeight / cellSize));

  const cache = getCache(canvas, width, height);
  if (!cache) {
    return { width, height, cells: 0, litRatio: 0 };
  }

  if (applyStyles) {
    // Hard cell edges on upscale. Without this the browser smooths the
    // low-res buffer and the ordered structure turns into grey mush.
    canvas.style.imageRendering = 'pixelated';
    canvas.style.width = '100%';
    canvas.style.height = '100%';
    canvas.style.display = 'block';
  }

  const inkPixel = parseColour(invert ? paper : ink);
  const paperPixel = parseColour(invert ? ink : paper);

  const { pixels } = cache;
  // Guard against a 1-cell axis: (w - 1) would be 0 and u would be NaN.
  const uScale = width > 1 ? 1 / (width - 1) : 0;
  const vScale = height > 1 ? 1 / (height - 1) : 0;
  const applyGamma = gamma !== 1;

  let lit = 0;
  let i = 0;

  for (let y = 0; y < height; y++) {
    const v = y * vScale;
    const row = (y & 7) << 3;
    for (let x = 0; x < width; x++, i++) {
      let value = fn(x * uScale, v, time) + bias;
      if (applyGamma) {
        value = value <= 0 ? 0 : Math.pow(value, gamma);
      }
      if (value > BAYER_8_THRESHOLDS[row | (x & 7)]!) {
        pixels[i] = inkPixel;
        lit++;
      } else {
        pixels[i] = paperPixel;
      }
    }
  }

  cache.ctx.putImageData(cache.imageData, 0, 0);

  const cells = width * height;
  return { width, height, cells, litRatio: cells === 0 ? 0 : lit / cells };
}

/** True when the user has asked the OS to reduce motion. */
export function prefersReducedMotion(): boolean {
  if (typeof window === 'undefined' || !window.matchMedia) return false;
  return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}

export type DitherLoopOptions = DitherOptions & {
  /** Multiplier on elapsed seconds before it reaches the field. Default 1. */
  speed?: number;
  /**
   * Frame budget. The loop skips rAF ticks to hold this rate; dither texture
   * reads well at low frame rates and it keeps the main thread free.
   * Default 30.
   */
  fps?: number;
  /**
   * Time passed to the field for the single static frame rendered when motion
   * is reduced. Default 0.
   */
  reducedMotionTime?: number;
  /** Re-render on element resize. Default true. */
  observeResize?: boolean;
  /**
   * Pause while the canvas is scrolled out of view. Default true.
   */
  pauseOffscreen?: boolean;
};

export type DitherLoopHandle = {
  /** Render a single frame immediately at the given time (defaults to now). */
  render: (time?: number) => void;
  start: () => void;
  stop: () => void;
  /** True when animating; false under reduced motion or after stop(). */
  readonly running: boolean;
  /** Swap the field without tearing down the buffer. */
  setField: (fn: FieldFn) => void;
  setOptions: (patch: Partial<DitherLoopOptions>) => void;
  destroy: () => void;
};

/**
 * Animate a field, honouring `prefers-reduced-motion` by rendering exactly one
 * static frame and never scheduling a rAF loop at all.
 *
 * Also pauses when the canvas leaves the viewport or the tab is hidden — an
 * animated full-bleed field that keeps integrating while invisible is pure
 * battery cost.
 */
export function createDitherLoop(
  canvas: HTMLCanvasElement,
  fn: FieldFn,
  opts: DitherLoopOptions = {}
): DitherLoopHandle {
  let field = fn;
  let options: DitherLoopOptions = { ...opts };
  let frame = 0;
  let startedAt = 0;
  let lastDrawn = -Infinity;
  /* Field-time accumulated across pauses, so an offscreen/hidden spell
     resumes the motion where it left off instead of snapping the field
     back to its boot frame. */
  let simBase = 0;
  let running = false;
  let visible = true;
  let destroyed = false;

  const reduced = prefersReducedMotion();

  const draw = (time: number) => {
    ditherToCanvas(canvas, field, { ...options, time });
  };

  const tick = (now: number) => {
    if (destroyed) return;
    frame = requestAnimationFrame(tick);
    const fps = options.fps ?? 30;
    const minDelta = fps > 0 ? 1000 / fps : 0;
    if (now - lastDrawn < minDelta) return;
    lastDrawn = now;
    if (!startedAt) startedAt = now;
    draw(simBase + ((now - startedAt) / 1000) * (options.speed ?? 1));
  };

  const start = () => {
    if (destroyed || running || reduced) return;
    running = true;
    startedAt = 0;
    lastDrawn = -Infinity;
    frame = requestAnimationFrame(tick);
  };

  const stop = () => {
    if (running && startedAt) {
      simBase +=
        ((performance.now() - startedAt) / 1000) * (options.speed ?? 1);
      startedAt = 0;
    }
    running = false;
    if (frame) cancelAnimationFrame(frame);
    frame = 0;
  };

  // Always paint one frame synchronously, before any rAF is scheduled.
  //
  // Under reduced motion this is the only frame there will ever be. Otherwise
  // it exists to size and style the canvas immediately: a canvas that has not
  // been drawn to yet keeps its default 300x150 backing store, which CSS then
  // stretches across the whole box, so deferring the first paint to rAF shows
  // a blank wrongly-scaled canvas for a frame.
  draw(reduced ? (options.reducedMotionTime ?? 0) : 0);

  let resizeObserver: ResizeObserver | undefined;
  if (
    (options.observeResize ?? true) &&
    typeof ResizeObserver !== 'undefined'
  ) {
    resizeObserver = new ResizeObserver(() => {
      if (destroyed) return;
      // A resize invalidates the buffer, so a paused/static canvas still needs
      // one fresh frame at its current time.
      if (!running) draw(reduced ? (options.reducedMotionTime ?? 0) : simBase);
    });
    resizeObserver.observe(canvas);
  }

  let intersectionObserver: IntersectionObserver | undefined;
  if (
    !reduced &&
    (options.pauseOffscreen ?? true) &&
    typeof IntersectionObserver !== 'undefined'
  ) {
    intersectionObserver = new IntersectionObserver((entries) => {
      visible = entries.some((e) => e.isIntersecting);
      if (visible && !document.hidden) start();
      else stop();
    });
    intersectionObserver.observe(canvas);
  }

  const onVisibility = () => {
    if (reduced) return;
    if (document.hidden) stop();
    else if (visible) start();
  };
  if (typeof document !== 'undefined') {
    document.addEventListener('visibilitychange', onVisibility);
  }

  if (!reduced) start();

  return {
    render: (time) => draw(time ?? 0),
    start,
    stop,
    get running() {
      return running;
    },
    setField: (next) => {
      field = next;
      if (!running) draw(simBase);
    },
    setOptions: (patch) => {
      options = { ...options, ...patch };
      if (!running) draw(reduced ? (options.reducedMotionTime ?? 0) : simBase);
    },
    destroy: () => {
      destroyed = true;
      stop();
      resizeObserver?.disconnect();
      intersectionObserver?.disconnect();
      if (typeof document !== 'undefined') {
        document.removeEventListener('visibilitychange', onVisibility);
      }
    },
  };
}

/* ------------------------------------------------------------------------ *
 * Field library
 *
 * Every field is a factory taking an all-optional options object, so
 * `radialBurst()` is valid and `radialBurst({ spokes: 14 })` tunes it. They
 * are plain closures over numbers — no allocation per call, safe to invoke
 * a few hundred thousand times a frame.
 * ------------------------------------------------------------------------ */

const TAU = Math.PI * 2;

function clamp01(x: number): number {
  return x < 0 ? 0 : x > 1 ? 1 : x;
}

function smoothstep(edge0: number, edge1: number, x: number): number {
  if (edge0 === edge1) return x < edge0 ? 0 : 1;
  const t = clamp01((x - edge0) / (edge1 - edge0));
  return t * t * (3 - 2 * t);
}

/** Deterministic 2D value hash, 0..1. Cheap integer bit-mixing, no tables. */
function hash2(x: number, y: number): number {
  let h = (Math.imul(x | 0, 374761393) + Math.imul(y | 0, 668265263)) | 0;
  h = Math.imul(h ^ (h >>> 13), 1274126177);
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
}

/** Bilinear-interpolated value noise, 0..1. */
function valueNoise(x: number, y: number): number {
  const xi = Math.floor(x);
  const yi = Math.floor(y);
  const xf = x - xi;
  const yf = y - yi;
  const sx = xf * xf * (3 - 2 * xf);
  const sy = yf * yf * (3 - 2 * yf);
  const n00 = hash2(xi, yi);
  const n10 = hash2(xi + 1, yi);
  const n01 = hash2(xi, yi + 1);
  const n11 = hash2(xi + 1, yi + 1);
  const a = n00 + (n10 - n00) * sx;
  const b = n01 + (n11 - n01) * sx;
  return a + (b - a) * sy;
}

/** Fractal value noise, 0..1. */
function fbm(x: number, y: number, octaves: number): number {
  let sum = 0;
  let amp = 0.5;
  let norm = 0;
  let fx = x;
  let fy = y;
  for (let o = 0; o < octaves; o++) {
    sum += valueNoise(fx, fy) * amp;
    norm += amp;
    amp *= 0.5;
    fx *= 2.03;
    fy *= 2.01;
  }
  return norm === 0 ? 0 : sum / norm;
}

export type RadialBurstOptions = {
  /** Centre of the burst in 0..1 field space. Default 0.5, 0.5. */
  cx?: number;
  cy?: number;
  /** Number of angular streaks. Default 11. */
  spokes?: number;
  /** Turbulence applied to the streak angle. 0 gives clean rays. Default 0.55. */
  turbulence?: number;
  /** Layers of streaks integrated per pixel. Higher is richer and dearer. Default 3. */
  layers?: number;
  /**
   * Radius of the dark core, 0..1. The reference composition frames itself on
   * a deliberate hole at the convergence point. Default 0.13.
   */
  coreRadius?: number;
  /** Falloff exponent with radius. Higher fades the burst sooner. Default 1.35. */
  falloff?: number;
  /** Overall gain. Default 1. */
  intensity?: number;
  /** Aspect correction; set to canvasWidth/canvasHeight to keep rays straight. Default 1. */
  aspect?: number;
  /** Radians per second of rotation. Default 0.05. */
  spin?: number;
  /** Rate at which the turbulence field evolves. Default 0.12. */
  drift?: number;
  /**
   * Octaves of noise in the streak warp. This is the field's dominant cost —
   * it is evaluated once per layer per pixel — so it is the first dial to turn
   * down. 2 is visually near-indistinguishable from 3 at dither resolution.
   * Default 2.
   */
  warpOctaves?: number;
};

/**
 * Radial burst — the prismatic light field reduced to a single 1-bit channel.
 *
 * The reference is a raymarched shader that accumulates `palette / (d*d*z)`
 * along several traces through a noise-warped domain, so brightness spikes
 * into anisotropic streaks wherever the field distance collapses, converging
 * on a dark centre. Dropping colour leaves exactly that luminance structure:
 * angular streak density, integrated over a few layers, punched through by a
 * dark core and tone-mapped so the highlights do not clip flat.
 */
export function radialBurst(opts: RadialBurstOptions = {}): FieldFn {
  const {
    cx = 0.5,
    cy = 0.5,
    spokes = 11,
    turbulence = 0.55,
    layers = 3,
    coreRadius = 0.13,
    falloff = 1.35,
    intensity = 1,
    aspect = 1,
    spin = 0.05,
    drift = 0.12,
    warpOctaves = 2,
  } = opts;

  // Per-layer constants hoisted out of the per-pixel loop. Each layer stands
  // for one trace in the reference shader: its own angular frequency, radial
  // decay rate, noise offset and weight.
  const layerCount = Math.max(1, Math.floor(layers));
  const exponent = falloff * 2;
  const freqs = new Float64Array(layerCount);
  const radialK = new Float64Array(layerCount);
  const weights = new Float64Array(layerCount);
  const warpScale = new Float64Array(layerCount);
  const phases = new Float64Array(layerCount);
  let weightSum = 0;
  for (let i = 0; i < layerCount; i++) {
    freqs[i] = spokes * (1 + i * 0.47) * 0.5;
    // (r * k)^e === r^e * k^e, so the per-layer part folds into a constant and
    // the per-pixel work drops from one pow per layer to one pow per pixel.
    radialK[i] = Math.pow(3.4 + i * 0.8, exponent);
    weights[i] = 1 - i * 0.22;
    // Each layer reads the shared turbulence field at its own amplitude, and
    // an additive angular phase keeps the layers from lining up. Both are
    // free: no extra noise evaluation.
    warpScale[i] = 1 + i * 0.37;
    phases[i] = i * 2.399963;
    weightSum += weights[i]!;
  }
  // Normalising by the weight sum (not the layer count) keeps overall
  // brightness stable when `layers` changes.
  const gain = (4.9 / weightSum) * intensity;

  return (u, v, t) => {
    const dx = (u - cx) * aspect;
    const dy = v - cy;
    const r = Math.sqrt(dx * dx + dy * dy);
    const angle = Math.atan2(dy, dx) + t * spin;

    // Hoisted per-pixel: these were being recomputed inside the layer loop,
    // which meant three cos + three sin + three pow per pixel instead of one.
    const noiseX = Math.cos(angle) * 2.4;
    const noiseY = Math.sin(angle) * 2.4 + r * 3.1 - t * drift;
    const radialPow = Math.pow(r, exponent);

    // ONE turbulence sample per pixel, shared by every layer. The reference
    // shader deforms a single domain and traces through it, so a shared warp
    // field is the faithful reduction as well as the cheap one: sampling the
    // noise per layer instead made the field ~3x dearer (the fbm was 12ms of
    // a 22ms 144k-cell frame) for no visible gain, because the layers already
    // differ in frequency, amplitude and phase.
    const baseWarp =
      turbulence === 0
        ? 0
        : (fbm(noiseX, noiseY, warpOctaves) - 0.5) * turbulence * TAU;

    let sum = 0;
    for (let i = 0; i < layerCount; i++) {
      // Streak profile: a sharpened |sin| ridge, cubed. The exponent
      // concentrates energy into thin filaments, standing in for the
      // reference shader's 1/d^2 spike. Cubing by multiplication rather than
      // Math.pow is measurably cheaper at this call volume.
      const q =
        1 -
        Math.abs(
          Math.sin((angle + baseWarp * warpScale[i]!) * freqs[i]! + phases[i]!)
        );
      const streak = q * q * q;

      // Radial energy: bright just outside the core, decaying outward.
      sum += (streak * weights[i]!) / (1 + radialPow * radialK[i]!);
    }

    let value = sum * gain;

    // Dark core at the convergence point, and a soft outer vignette so the
    // field resolves to paper at the frame edge rather than being clipped.
    value *= smoothstep(coreRadius * 0.35, coreRadius, r);
    value *= 1 - smoothstep(0.42, 0.78, r) * 0.85;

    // Tone map: tanh-shaped roll-off keeps filament cores under 1 so the
    // dither still has headroom to render structure inside the brightest areas.
    return value / (1 + value);
  };
}

export type GlobeOptions = {
  /** Centre in 0..1 field space. Default 0.5, 0.5. */
  cx?: number;
  cy?: number;
  /** Sphere radius in 0..1 field space. Default 0.38. */
  radius?: number;
  /** Light direction; normalised internally. Default (-0.45, -0.62, 0.65). */
  lightX?: number;
  lightY?: number;
  lightZ?: number;
  /** Ambient floor added to the lambert term, 0..1. Default 0.08. */
  ambient?: number;
  /** Rim light strength at the silhouette edge. Default 0.22. */
  rim?: number;
  /** Latitude/longitude graticule strength, 0 disables. Default 0.3. */
  graticule?: number;
  /** Meridians and parallels drawn when graticule > 0. Defaults 12 and 7. */
  meridians?: number;
  parallels?: number;
  /** Continent-ish landmass contrast from noise, 0 disables. Default 0.22. */
  landmass?: number;
  /** Radians per second of spin about the polar axis. Default 0.18. */
  spin?: number;
  /** Aspect correction; canvasWidth/canvasHeight keeps the globe circular. Default 1. */
  aspect?: number;
  /** Axial tilt in radians. Default 0.41 (~23.4 degrees). */
  tilt?: number;
};

/**
 * Sphere with lambert shading — a globe, dithered.
 *
 * Analytic ray-sphere intersection for an orthographic camera, which for a
 * unit sphere at the origin collapses to `z = sqrt(1 - x^2 - y^2)`; that
 * position *is* the surface normal, so the lambert term is a single dot
 * product. Optional graticule and noise landmass ride on top as multipliers,
 * giving the dither something to articulate besides a smooth gradient.
 */
export function globe(opts: GlobeOptions = {}): FieldFn {
  const {
    cx = 0.5,
    cy = 0.5,
    radius = 0.38,
    lightX = -0.45,
    lightY = -0.62,
    lightZ = 0.65,
    ambient = 0.08,
    rim = 0.22,
    graticule = 0.3,
    meridians = 12,
    parallels = 7,
    landmass = 0.22,
    spin = 0.18,
    aspect = 1,
    tilt = 0.41,
  } = opts;

  const lightLen = Math.hypot(lightX, lightY, lightZ) || 1;
  const lx = lightX / lightLen;
  const ly = lightY / lightLen;
  const lz = lightZ / lightLen;
  const cosTilt = Math.cos(tilt);
  const sinTilt = Math.sin(tilt);

  return (u, v, t) => {
    const px = ((u - cx) * aspect) / radius;
    const py = (v - cy) / radius;
    const d2 = px * px + py * py;
    if (d2 >= 1) return 0; // off the sphere: paper

    // Orthographic hit point on the unit sphere; also the normal.
    const nz = Math.sqrt(1 - d2);
    const nx = px;
    const ny = py;

    // Lambert.
    let light = nx * lx + ny * ly + nz * lz;
    light = light < 0 ? 0 : light;
    let value = ambient + (1 - ambient) * light;

    // Rim: brighten the silhouette so the sphere separates from the paper.
    if (rim !== 0) value += rim * Math.pow(d2, 3.5);

    if (graticule !== 0 || landmass !== 0) {
      // Un-tilt into the sphere's own frame so lat/lon follow the axis.
      const ay = ny * cosTilt - nz * sinTilt;
      const az = ny * sinTilt + nz * cosTilt;
      const lat = Math.asin(Math.max(-1, Math.min(1, ay)));
      const lon = Math.atan2(nx, az) + t * spin;

      if (landmass !== 0) {
        // Sample noise in lat/lon so the pattern rotates with the surface
        // instead of sliding across it.
        const land = fbm(
          Math.cos(lon) * 2.2 + 4.1,
          Math.sin(lon) * 2.2 + lat * 2.6,
          4
        );
        value *= 1 - landmass + landmass * 2 * smoothstep(0.42, 0.62, land);
      }

      if (graticule !== 0) {
        const lonLine =
          1 - Math.pow(Math.abs(Math.sin(lon * meridians * 0.5)), 0.14);
        const latLine =
          1 - Math.pow(Math.abs(Math.sin(lat * parallels)), 0.14);
        // Foreshortening: only draw lines that face the camera, so the
        // graticule does not pile up into a solid band at the limb.
        const facing = nz;
        value *= 1 - Math.max(lonLine, latLine) * graticule * facing;
      }
    }

    // Feather the silhouette by one cell's worth so the edge dithers rather
    // than aliasing into a hard jagged circle.
    return clamp01(value) * smoothstep(1, 0.985, d2);
  };
}

export type StreakBandsOptions = {
  /** Number of bands down the height. Default 22. */
  bands?: number;
  /** Duty cycle of a band, 0..1. Default 0.44. */
  duty?: number;
  /**
   * Edge softness of each band, as a fraction of the duty. 0 gives hard bars,
   * which mostly defeats the point — the dither can only make texture out of
   * intermediate values, so a soft band edge is what produces the halftone
   * fringe instead of a solid rule. Default 0.62.
   */
  softness?: number;
  /** Horizontal wave amplitude applied to band position. Default 0.13. */
  waviness?: number;
  /** Horizontal frequency of that wave. Default 1.6. */
  waveFrequency?: number;
  /** Noise break-up of band coverage, 0 disables. Default 0.4. */
  turbulence?: number;
  /** Left-to-right coverage ramp: bands fade out across the frame. Default 0.5. */
  taper?: number;
  /** Vertical drift in bands per second. Default 0.06. */
  speed?: number;
};

/**
 * Horizontal streak bands — scanline-like strata that break up into dither
 * grain as they fade.
 *
 * The band coordinate is warped horizontally by a low-frequency wave so the
 * strata are not dead-straight rulings, and coverage is modulated by noise
 * and an optional horizontal taper. Because the underlying value is a smooth
 * ramp rather than a hard mask, the ordered dither renders the fade as a
 * progressive thinning of cells — the effect that makes this read as printed
 * texture instead of as CSS repeating-linear-gradient.
 */
export function streakBands(opts: StreakBandsOptions = {}): FieldFn {
  const {
    bands = 22,
    duty = 0.44,
    softness = 0.62,
    waviness = 0.13,
    waveFrequency = 1.6,
    turbulence = 0.32,
    taper = 0.5,
    speed = 0.06,
  } = opts;

  return (u, v, t) => {
    const wave =
      waviness === 0
        ? 0
        : Math.sin(u * waveFrequency * TAU + t * 0.35) * waviness +
          Math.sin(u * waveFrequency * 2.7 * TAU - t * 0.21) * waviness * 0.4;

    const pos = (v + wave / bands) * bands + t * speed;
    const phase = pos - Math.floor(pos); // 0..1 within the band

    // Symmetric distance from the band centre, so softness feathers both edges.
    const dist = Math.abs(phase - 0.5) * 2; // 0 at centre, 1 at band edge
    const edge = duty;
    const value =
      softness === 0
        ? dist < edge
          ? 1
          : 0
        : 1 - smoothstep(edge - softness * edge, edge + softness * edge, dist);

    let coverage = value;
    if (turbulence !== 0) {
      const n = fbm(u * 3.2, v * 9.0 - t * 0.25, 3);
      coverage *= 1 - turbulence + turbulence * 2 * n;
    }
    if (taper !== 0) {
      coverage *= 1 - taper * smoothstep(0.15, 1, u);
    }
    return clamp01(coverage);
  };
}

export type GradientRampOptions = {
  /** Ramp direction in radians; 0 is left-to-right, PI/2 top-to-bottom. Default 0. */
  angle?: number;
  /** Value at the start and end of the ramp. Defaults 0 and 1. */
  from?: number;
  to?: number;
  /** Exponent on the ramp parameter; >1 pushes the transition later. Default 1. */
  exponent?: number;
  /** Ease the ramp with smoothstep instead of running linear. Default false. */
  smooth?: boolean;
  /** Sinusoidal wobble on the ramp, 0 disables. Default 0. */
  wobble?: number;
  /** Frequency of that wobble across the ramp axis. Default 3. */
  wobbleFrequency?: number;
  /** Drift of the ramp per second. Default 0. */
  speed?: number;
};

/**
 * Gradient ramp — the calibration field and the workhorse.
 *
 * A linear ramp is the honest test of an ordered dither: it should walk
 * cleanly through all 65 achievable levels with no banding beyond the cell
 * quantisation itself, and the 8x8 tile structure should be plainly visible
 * in the midtones.
 */
export function gradientRamp(opts: GradientRampOptions = {}): FieldFn {
  const {
    angle = 0,
    from = 0,
    to = 1,
    exponent = 1,
    smooth = false,
    wobble = 0,
    wobbleFrequency = 3,
    speed = 0,
  } = opts;

  const dirX = Math.cos(angle);
  const dirY = Math.sin(angle);
  // Project onto the ramp axis and normalise so the unit square maps to 0..1
  // whatever the angle.
  const span = Math.abs(dirX) + Math.abs(dirY) || 1;
  const offset = (Math.min(0, dirX) + Math.min(0, dirY)) / span;

  return (u, v, t) => {
    let p = (u * dirX + v * dirY) / span - offset + t * speed;
    if (wobble !== 0) {
      p += Math.sin((p * wobbleFrequency + t * 0.2) * TAU) * wobble;
    }
    p = clamp01(p);
    if (exponent !== 1) p = Math.pow(p, exponent);
    if (smooth) p = p * p * (3 - 2 * p);
    return from + (to - from) * p;
  };
}

export type GlyphFieldOptions = {
  /** The letterform(s) to render. Required. */
  text: string;
  /**
   * CSS font shorthand *without* a size — the size is chosen to fit the SDF
   * grid. Default '900 {size}px ui-sans-serif, system-ui, sans-serif' style
   * weight/family; pass e.g. '700 {size}px "Instrument Serif", serif'.
   * The literal token `{size}` is substituted; if absent, the family string is
   * used as-is with the size prepended.
   */
  font?: string;
  /**
   * Resolution of the square SDF grid. 256 is ample for display type; the
   * cost is one-time at construction. Default 256.
   */
  resolution?: number;
  /**
   * Width in grid cells of the soft ramp either side of the outline. Larger
   * gives a wider dithered fringe. Default 14.
   */
  softness?: number;
  /**
   * 'fill' renders a solid glyph with a dithered fringe. 'outline' renders
   * only a band along the contour. 'glow' ramps outward from the glyph into
   * paper. Default 'fill'.
   */
  mode?: 'fill' | 'outline' | 'glow';
  /** Band half-width in grid cells when mode is 'outline'. Default 6. */
  outlineWidth?: number;
  /** Distance in grid cells over which 'glow' decays. Default 60. */
  glowRadius?: number;
  /** Fraction of the grid left as margin around the glyph, 0..0.5. Default 0.06. */
  padding?: number;
  /** Letter spacing in em. Default 0. */
  tracking?: number;
  /**
   * 'contain' preserves the letterform's proportions inside the field box
   * (requires `aspect`); 'stretch' maps the square SDF grid onto the whole box,
   * distorting the glyph to fit. Default 'contain' — a stretched letterform is
   * almost never what is wanted.
   */
  fit?: 'stretch' | 'contain';
  /**
   * Field box aspect ratio (canvasWidth / canvasHeight), used by 'contain' to
   * keep the glyph un-distorted. Default 1.
   */
  aspect?: number;
};

export type GlyphField = FieldFn & {
  /** Signed distance in grid cells at (u, v): negative inside the glyph. */
  signedDistance: (u: number, v: number) => number;
  /** Grid resolution actually used. */
  resolution: number;
};

/**
 * Build a signed-distance field from a letterform so type can be dithered.
 *
 * Rasterises the glyph once into an offscreen canvas, then runs an exact
 * Euclidean distance transform over the inside and the outside separately and
 * subtracts them. That gives a true signed distance, which is what makes the
 * result resolution-independent: the field can be sampled at any dither scale
 * and the edge ramp stays the same *visual* width, and modes like outline and
 * glow are then one-line functions of the distance.
 *
 * The alternative — sampling the rasterised alpha directly — only ever gives
 * you a 1-pixel-wide edge gradient, so at dither scale 3 the letterform's
 * contour aliases into hard jaggies with nothing for the ordered pattern to
 * articulate.
 *
 * Must run in a DOM environment. Call after `document.fonts.ready` if the
 * letterform depends on a webfont, otherwise the metrics come from the
 * fallback family.
 */
export function makeGlyphField(opts: GlyphFieldOptions): GlyphField {
  const {
    text,
    font = '900 {size}px ui-sans-serif, system-ui, sans-serif',
    resolution = 256,
    softness = 14,
    mode = 'fill',
    outlineWidth = 6,
    glowRadius = 60,
    padding = 0.06,
    tracking = 0,
    fit = 'contain',
    aspect = 1,
  } = opts;

  const size = Math.max(8, Math.floor(resolution));
  const inside = new Float64Array(size * size);

  // --- rasterise -------------------------------------------------------
  const mask = new Uint8Array(size * size);
  if (typeof document !== 'undefined') {
    const raster = document.createElement('canvas');
    raster.width = size;
    raster.height = size;
    const ctx = raster.getContext('2d', { willReadFrequently: true });
    if (ctx) {
      ctx.clearRect(0, 0, size, size);
      ctx.fillStyle = '#fff';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'alphabetic';
      if (tracking !== 0) {
        // letterSpacing is not in older lib.dom typings; feature-detect.
        const withSpacing = ctx as CanvasRenderingContext2D & {
          letterSpacing?: string;
        };
        if ('letterSpacing' in withSpacing) {
          withSpacing.letterSpacing = `${tracking}em`;
        }
      }

      const usable = size * (1 - padding * 2);

      // Binary-search the font size that makes the glyph's tight ink box fill
      // the usable area. Measuring beats guessing from em size: display faces
      // vary wildly in cap height and overshoot.
      const setFont = (px: number) => {
        ctx.font = font.includes('{size}')
          ? font.replace('{size}', String(px))
          : `${px}px ${font}`;
      };
      const inkBox = (px: number) => {
        setFont(px);
        const m = ctx.measureText(text);
        const w =
          (m.actualBoundingBoxLeft ?? 0) + (m.actualBoundingBoxRight ?? 0);
        const h =
          (m.actualBoundingBoxAscent ?? 0) + (m.actualBoundingBoxDescent ?? 0);
        return { w: w || m.width, h: h || px, m };
      };

      let px = usable;
      for (let iter = 0; iter < 24; iter++) {
        const { w, h } = inkBox(px);
        const scale = Math.min(usable / (w || 1), usable / (h || 1));
        if (Math.abs(scale - 1) < 0.002) break;
        px = Math.max(4, Math.min(size * 8, px * scale));
      }

      const { m } = inkBox(px);
      const ascent = m.actualBoundingBoxAscent ?? px * 0.7;
      const descent = m.actualBoundingBoxDescent ?? 0;
      const left = m.actualBoundingBoxLeft ?? 0;
      const right = m.actualBoundingBoxRight ?? m.width;
      // Centre the tight INK box, not the advance box — side bearings and
      // overshoot would otherwise push the glyph off-centre.
      //
      // textAlign is 'center', so the anchor is already the centre of the
      // advance box and the bounding-box metrics are measured relative to it:
      // the ink spans [anchor - left, anchor + right]. Its centre therefore
      // sits at anchor + (right - left) / 2, so to land that centre on the
      // grid centre the anchor goes to size/2 - (right - left)/2. Adding
      // `left` on top of this (the correct term for textAlign 'left') shifts
      // the glyph right by half its width and clips it.
      ctx.fillText(
        text,
        size / 2 - (right - left) / 2,
        size / 2 + (ascent - descent) / 2
      );

      const data = ctx.getImageData(0, 0, size, size).data;
      for (let i = 0, p = 3; i < mask.length; i++, p += 4) {
        mask[i] = (data[p] ?? 0) >= 128 ? 1 : 0;
      }
    }
  }

  // --- exact Euclidean distance transform -------------------------------
  // Felzenszwalb & Huttenlocher: the squared EDT is separable, and each 1D
  // pass is the lower envelope of a set of parabolas, computable in O(n).
  const INF = 1e20;

  const edt1d = (f: Float64Array, n: number, d: Float64Array) => {
    const vtx = new Int32Array(n);
    const z = new Float64Array(n + 1);
    let k = 0;
    vtx[0] = 0;
    z[0] = -INF;
    z[1] = INF;
    for (let q = 1; q < n; q++) {
      let s =
        (f[q]! + q * q - (f[vtx[k]!]! + vtx[k]! * vtx[k]!)) /
        (2 * q - 2 * vtx[k]!);
      while (s <= z[k]!) {
        k--;
        s =
          (f[q]! + q * q - (f[vtx[k]!]! + vtx[k]! * vtx[k]!)) /
          (2 * q - 2 * vtx[k]!);
      }
      k++;
      vtx[k] = q;
      z[k] = s;
      z[k + 1] = INF;
    }
    k = 0;
    for (let q = 0; q < n; q++) {
      while (z[k + 1]! < q) k++;
      const dq = q - vtx[k]!;
      d[q] = dq * dq + f[vtx[k]!]!;
    }
  };

  /** Squared EDT of the set where `isSeed(i)` is true. */
  const edt2d = (isSeed: (i: number) => boolean): Float64Array => {
    const grid = new Float64Array(size * size);
    for (let i = 0; i < grid.length; i++) grid[i] = isSeed(i) ? 0 : INF;

    const line = new Float64Array(size);
    const out = new Float64Array(size);

    // Columns.
    for (let x = 0; x < size; x++) {
      for (let y = 0; y < size; y++) line[y] = grid[y * size + x]!;
      edt1d(line, size, out);
      for (let y = 0; y < size; y++) grid[y * size + x] = out[y]!;
    }
    // Rows.
    for (let y = 0; y < size; y++) {
      const base = y * size;
      for (let x = 0; x < size; x++) line[x] = grid[base + x]!;
      edt1d(line, size, out);
      for (let x = 0; x < size; x++) grid[base + x] = out[x]!;
    }
    return grid;
  };

  const distOutside = edt2d((i) => mask[i] === 1); // distance to ink
  const distInside = edt2d((i) => mask[i] === 0); // distance to paper

  // Signed distance in grid cells: negative inside the glyph.
  for (let i = 0; i < inside.length; i++) {
    inside[i] =
      mask[i] === 1 ? -Math.sqrt(distInside[i]!) : Math.sqrt(distOutside[i]!);
  }

  /**
   * Bilinear sample of the SDF, so it stays smooth at any dither scale.
   *
   * Under 'contain' the square grid is inset into the (possibly non-square)
   * field box, which leaves field space outside the grid. Rather than cutting
   * the distance off there — which would slice a hard straight edge through a
   * glow halo — the sample is clamped to the grid edge and the distance to the
   * grid boundary is added back. The result stays monotonic and continuous, so
   * outward ramps keep falling off correctly past the grid.
   */
  const sampleSDF = (u: number, v: number): number => {
    let su = u;
    let sv = v;
    if (fit === 'contain') {
      // Inset the square grid into the box's shorter axis.
      if (aspect >= 1) su = (u - 0.5) * aspect + 0.5;
      else sv = (v - 0.5) / aspect + 0.5;
    }

    // How far outside the grid we are, in normalised units.
    const ox = su < 0 ? -su : su > 1 ? su - 1 : 0;
    const oy = sv < 0 ? -sv : sv > 1 ? sv - 1 : 0;
    const outside =
      ox === 0 && oy === 0 ? 0 : Math.sqrt(ox * ox + oy * oy) * (size - 1);

    const gx = clamp01(su) * (size - 1);
    const gy = clamp01(sv) * (size - 1);

    const x0 = Math.floor(gx);
    const y0 = Math.floor(gy);
    const x1 = Math.min(size - 1, x0 + 1);
    const y1 = Math.min(size - 1, y0 + 1);
    const fx = gx - x0;
    const fy = gy - y0;
    const a = inside[y0 * size + x0]!;
    const b = inside[y0 * size + x1]!;
    const c = inside[y1 * size + x0]!;
    const d = inside[y1 * size + x1]!;
    const top = a + (b - a) * fx;
    const bottom = c + (d - c) * fx;
    return top + (bottom - top) * fy + outside;
  };

  const evaluate: FieldFn = (u, v) => {
    const sd = sampleSDF(u, v);

    if (mode === 'outline') {
      // Band centred on the contour: 1 on the line, ramping to 0 either side.
      const band = Math.abs(sd) - outlineWidth;
      return 1 - smoothstep(-softness * 0.5, softness * 0.5, band);
    }
    if (mode === 'glow') {
      // Solid inside, decaying outward — a halo the dither thins out.
      if (sd <= 0) return 1;
      return 1 - smoothstep(0, glowRadius, sd);
    }
    // 'fill': solid inside with a soft fringe straddling the outline, which
    // is what gives the letterform a dithered edge instead of a hard one.
    return 1 - smoothstep(-softness * 0.5, softness * 0.5, sd);
  };

  return Object.assign(evaluate, {
    signedDistance: sampleSDF,
    resolution: size,
  });
}

/* ------------------------------------------------------------------------ *
 * Combinators — fields are just functions, so they compose.
 * ------------------------------------------------------------------------ */

/** Multiply fields together (intersection / masking). */
export function multiplyFields(...fields: FieldFn[]): FieldFn {
  return (u, v, t) => {
    let out = 1;
    for (let i = 0; i < fields.length; i++) out *= fields[i]!(u, v, t);
    return out;
  };
}

/** Take the maximum of fields (union). */
export function maxFields(...fields: FieldFn[]): FieldFn {
  return (u, v, t) => {
    let out = 0;
    for (let i = 0; i < fields.length; i++) {
      const value = fields[i]!(u, v, t);
      if (value > out) out = value;
    }
    return out;
  };
}

/** Linear blend between two fields. */
export function mixFields(a: FieldFn, b: FieldFn, amount: number): FieldFn {
  return (u, v, t) => {
    const av = a(u, v, t);
    return av + (b(u, v, t) - av) * amount;
  };
}

/** Remap a field's output through a scalar function. */
export function mapField(
  field: FieldFn,
  transform: (value: number) => number
): FieldFn {
  return (u, v, t) => transform(field(u, v, t));
}
