/**
 * The marks behind /marks: the speed set for General Translation, seven
 * marks in one register, and the two survivors of the earlier round, each
 * a public SVG in currentColor under public/marks with its thesis,
 * construction and use notes as data. Pure data and types, no React, no
 * DOM, so the server page can read the files and the client viewer can lay
 * them out from the same list.
 *
 * The register comes from a race-type reference Kevin brought: wide
 * letters, a forward slant, one horizontal cut through the letters, and
 * speed bars that lead into the first letter. Every mark is black and
 * white, one color, and takes the ink of whatever it sits on. The seven
 * speed files are generated by scripts/build-speed-marks.mjs (pnpm
 * build:marks) with tight viewBoxes, so the viewer sizes each by height
 * and its own aspect. Two-way and Globe G keep their construction
 * overlays from the earlier round and stand at the end for comparison.
 * The current doubled-line monogram is kept only as REFERENCE_MARK, the
 * memory the marks are measured against, never as a candidate.
 */

/** The two families: the speed register, and the picture marks of the earlier round. */
export type MarkFamily = 'speed' | 'picture';

/** What the mark is: the letters alone, or the letters with the name (or as a rendering of the name). */
export type MarkKind = 'monogram' | 'wordmark';

export type Mark = {
  /** the file stem under public/marks; unique, and what the hash names */
  id: string;
  name: string;
  family: MarkFamily;
  kind: MarkKind;
  /** the mark in one or two sentences */
  thesis: string;
  /** the geometry: units, skew, cuts, faces, how the file is built */
  construction: string;
  /** how it behaves at small sizes and where it goes */
  use: string;
  /** the clean mark, a public path: /marks/<id>.svg */
  file: string;
  /** the construction overlay, a public path, for the marks of the earlier round */
  constructionFile?: string;
  /** the plain characters, a public path, for the ASCII rendering */
  textFile?: string;
};

/** A mark's files as read from disk by the server page, and the aspect of its viewBox (width over height). */
export type MarkArt = { clean: string; construction?: string; aspect: number };

/** One rule of the register; the first section lists them as ruled rows. */
export type MarkRule = { id: string; name: string; text: string };

export const MARK_FAMILIES: readonly { id: MarkFamily; label: string; principle: string }[] = [
  {
    id: 'speed',
    label: 'Speed',
    principle: 'Wide letters, a forward slant, one cut through the letters, and speed bars into the first letter.',
  },
  {
    id: 'picture',
    label: 'Picture',
    principle: 'The picture lives in the letters.',
  },
];

/** The heights a monogram is shown at, in CSS pixels; 16 is the favicon, 128 the app icon on a phone. */
export const MARK_SIZES: readonly number[] = [16, 24, 32, 64, 128];

/** The heights a wordmark is shown at, in CSS pixels: the cap of a header, a plate, a slide. */
export const WORDMARK_SIZES: readonly number[] = [48, 96, 144];

/** The rules of the register, in the order the first section lists them. */
export const MARK_RULES: readonly MarkRule[] = [
  {
    id: 'wide',
    name: 'Wide letters',
    text: 'Every letter is wider than it is tall. The monogram builds G and T from rectangles on a 120 unit cap, the plate sets GT in Orbitron Black, and the wordmarks set the name in Anybody at width 150, the widest instance of the face.',
  },
  {
    id: 'slant',
    name: 'A forward slant',
    text: 'The letters lean forward. The monogram and everything made from it sit under a 12 degree skew, the plate under 14 degrees, and the livery stack uses the italic of its face with a slash at 22 degrees across both lines. Double cut stands upright and is the one exception.',
  },
  {
    id: 'cut',
    name: 'One cut',
    text: 'One horizontal cut runs through the letters at mid cap height. On the monogram the cut is 8 units on a 120 unit cap and splits the middle speed bar in two. The livery stack cuts each of its two lines once. Double cut carries two cuts at 40 and 60 percent of the cap height, each 7 percent of the cap thick, and takes its speed from them.',
  },
  {
    id: 'bars',
    name: 'Speed bars',
    text: 'Three bars of different lengths lead into the first letter from the left. On the monogram they are the stem of the G combed into bars 20, 80 and 50 units long past the stem, at the top arm, at mid height and at the bottom arm. The dither and the ASCII keep them solid because their density is 1 across the left third of the width. The plate, double cut and the livery stack carry no bars.',
  },
  {
    id: 'one-color',
    name: 'One color',
    text: 'Every file is one color in currentColor: one path, or one masked group where the letters or the cuts are holes. There is no second tone, no gradient, no stroke and no shadow, so the mark takes the ink of whatever it sits on. The dither and the ASCII get their gray from the density of their cells.',
  },
  {
    id: 'grounds',
    name: 'Paper and ink',
    text: 'The same file positive and reversed, ink on paper and paper on ink, with no redraw for either ground. The plate is the one mark that brings its own ground, because its letters and its stripes are holes: on paper it is an ink plate, on ink a paper plate. The theme switch swaps the grounds on this page.',
  },
];

/** The faces behind the speed set; the register section closes with this note. */
export const MARK_FACES =
  'The faces are Michroma, Orbitron and Anybody, from Google Fonts under the SIL Open Font License. scripts/build-speed-marks.mjs converts every string to outlines at build time, so each file is geometry and the site loads none of the three.';

type MarkInput = Omit<Mark, 'file' | 'constructionFile' | 'textFile'> & {
  /** the mark has a construction overlay at /marks/<id>-construction.svg */
  overlay?: true;
  /** the mark has its plain characters at /marks/<id>.txt */
  text?: true;
};

function mark({ overlay, text, ...rest }: MarkInput): Mark {
  return {
    ...rest,
    file: `/marks/${rest.id}.svg`,
    ...(overlay ? { constructionFile: `/marks/${rest.id}-construction.svg` } : {}),
    ...(text ? { textFile: `/marks/${rest.id}.txt` } : {}),
  };
}

/** The nine marks in the page's order: the speed set from the monogram out, then the two survivors. */
export const MARKS: readonly Mark[] = [
  mark({
    id: 'bar-monogram',
    name: 'Bar monogram',
    family: 'speed',
    kind: 'monogram',
    thesis:
      'GT from ten rectangles under a 12 degree skew. The stem of the G is combed into three speed bars of different lengths, and one cut runs through both letters at mid height.',
    construction:
      'Ten rectangles on a 120 unit cap height under a 12 degree skew. The G is a stem, a top arm, a bottom arm, a chin and a right stem; the T is a crossbar and a stem; the three speed bars run 20, 80 and 50 units past the stem of the G at the top arm, at mid height and at the bottom arm. One 8 unit cut at mid height runs through both letters and splits the middle bar into two lines. The cut is applied to the geometry, so the file is plain polygons in one path, with no font, no mask and no id.',
    use:
      'There is no font in the file; the letters are geometry, so the mark holds at 16px and reads in either polarity. At 16px the cut and the thin bars fall to one pixel and the two letters carry the mark; from 32px the three bars read as bars.',
  }),
  mark({
    id: 'bar-monogram-lockup',
    name: 'Bar monogram lockup',
    family: 'speed',
    kind: 'wordmark',
    thesis: 'The monogram over the name in Michroma at a fifth of the cap height, letter-spaced to the width of the monogram.',
    construction:
      'The monogram unchanged, and GENERAL TRANSLATION in Michroma at 24 units, a fifth of the 120 unit cap, set 46 units under it and letter-spaced so the name spans the width of the monogram, speed bars included. The name is converted to outlines at build time, so the file is two paths and no font.',
    use:
      'For sign-in plates, deck openers and anywhere the mark stands alone with room under it. The name is small: its font size is an eighth of the height of the lockup, so a 96px lockup sets the name at 12px, and the monogram alone serves the sizes under that.',
  }),
  mark({
    id: 'plate-inverted',
    name: 'Plate',
    family: 'speed',
    kind: 'monogram',
    thesis:
      'GT in Orbitron Black cut out of a rounded plate under a 14 degree skew, with a hazard stripe clipped to the right end of the plate. The letters and the stripes are holes, so the ground shows through them.',
    construction:
      'A 320 by 120 plate with 12 unit corners, skewed 14 degrees about its bottom edge. GT is set in Orbitron Black at 90 units and cut out of the plate through a mask; the hazard stripe is bars 9 units wide on an 18 unit period at 35 degrees, clipped to the right 74 units of the plate and carried as holes of the same evenodd path. The file is one masked path in currentColor.',
    use:
      'The one direction that brings its own ground: on paper it is an ink plate, on ink a paper plate. It suits avatars, badges and the CLI banner, where a mark needs an edge of its own. At 16px the stripes merge into a gray end and the letters hold as two open counters; the stripe reads from about 48px.',
  }),
  mark({
    id: 'double-cut',
    name: 'Double cut',
    family: 'speed',
    kind: 'wordmark',
    thesis: 'GENERAL TRANSLATION in Anybody at width 150, black and upright, with two cuts through the line.',
    construction:
      'One line of Anybody Black at width 150, upright, at 100 units. Two cuts at 40 and 60 percent of the cap height, each 7 percent of the cap thick, are subtracted through a mask that spans the whole line. The letters are outlines from the build script; the file is one masked path and no font.',
    use:
      'The calmest of the set; the pair of cuts reads as speed without a slant. The line is 25 times wider than its cap, so it is for headers, footers, sleeves and the top of a document, and on this sheet it takes the full width. The cuts close below about 16px of cap height, where they fall under one pixel.',
  }),
  mark({
    id: 'livery-stack',
    name: 'Livery stack',
    family: 'speed',
    kind: 'wordmark',
    thesis: 'GENERAL over TRANSLATION in Anybody italics, a cut through each line and one forward slash across both.',
    construction:
      'GENERAL in Anybody Black Italic at width 150 and 150 units, over TRANSLATION in the Medium Italic sized to the same width with 2 units of letter spacing and a 40 unit gap between the lines. A cut runs through each line at mid cap height, and one slash at 22 degrees, 9 units wide, crosses both lines at 57 percent of the width. The cuts and the slash are subtracted through a mask; the file is one masked group of two paths.',
    use:
      'The loudest direction, for a livery, a jacket or a full-bleed slide. The slash stays one cut wide; wider, it turns into a stripe. Below about 48px the slash and the cuts fall under one pixel and close, so the stack is for large sizes.',
  }),
  mark({
    id: 'bar-monogram-dithered',
    name: 'Bar monogram, dithered',
    family: 'speed',
    kind: 'wordmark',
    thesis:
      'The monogram rasterised to square cells and printed through the 8 by 8 Bayer screen, solid at the left and thinning to the right.',
    construction:
      'The monogram sampled on a grid of 240 by 59 square cells, 16 samples per cell. A cell prints when more than half of it lies inside the monogram and the 8 by 8 Bayer screen passes it against a density that is 1 across the left third of the width and falls in a straight line to 0.18 at the right edge; 5,154 cells print. Every printed cell is one unit square in one path, so the file is one color and one path.',
    use:
      'The deck’s dither, on the mark: solid at the left, cells at the right, ink on paper. It sizes by cell, so it is for heights of 59px and up, where a cell is one pixel; below that the cells merge to gray and the mark reads as the monogram with a soft right edge.',
  }),
  mark({
    id: 'bar-monogram-ascii',
    name: 'Bar monogram in ASCII',
    family: 'speed',
    kind: 'wordmark',
    text: true,
    thesis: 'The same grid at the aspect of a monospace cell, one @ per printed cell, solid at the left and dithering away to the right.',
    construction:
      'The monogram sampled on a grid whose cells have the aspect of a monospace character, three wide to five tall: 160 columns by 23 lines, one @ per printed cell, the same Bayer screen and the same density fall. The SVG sets each line as text in a monospace stack with textLength, so any monospace face fills the same width; the .txt file is the plain characters with the trailing spaces trimmed.',
    use:
      'For a code block, a README or the CLI banner: the .txt file is the characters, 160 columns wide, and the SVG stands in where text cannot be set. The characters need a monospace face; in a proportional face the columns drift and the mark breaks.',
  }),
  mark({
    id: 'two-way',
    name: 'Two-way',
    family: 'picture',
    kind: 'monogram',
    overlay: true,
    thesis:
      'The bar of the G and the crossbar of the T are one stroke, a two-way arrow that starts inside the counter of the G, leaves through the aperture, carries the stem of the T and ends past it. The exchange between two languages is the stroke both letters hang from.',
    construction:
      '16 unit grid, stroke 32 (2 units). G ring centered (80, 80), outer radius 80, inner 48; terminal cut radially at minus 50 degrees; the spur rises to y 96 where it meets the shaft. Shaft y 64 to 96 from x 72 to 224; triangular heads 32 long and 64 tall, with apexes at (40, 80) inside the counter and (256, 80) past the stem. Stem x 176 to 208 from the shaft down to y 256. The letters are staggered: the G occupies the top left 160 square and the T hangs from the arrow into the bottom right.',
    use: 'At 16px the heads flatten to a 2px bar with pointed ends; the ring, the bar and the long stem still read as G and T on both grounds. The arrow itself appears from about 48px.',
  }),
  mark({
    id: 'globe-g',
    name: 'Globe G',
    family: 'picture',
    kind: 'monogram',
    overlay: true,
    thesis:
      'The counter of the G is a globe drawn by the T standing inside it. The stem of the T is the central meridian running to the south pole, its crossbar spans the disc as a parallel and closes a polar cap, and the bar of the G is the equator from the meridian out through the ring.',
    construction:
      'Ring centered (128, 128), outer R 120, inner R 88, stroke 32: a monogram filling the square from 16 to 240. Crossbar y 64 to 96 as a chord from wall to wall, leaving a 24 unit cap above it; stem x 112 to 144 from y 64 down into the inner bottom of the ring; bar y 128 to 160 from the stem to the outer circle. The terminal is the underside of the crossbar extended through the ring at y 96, so the mouth is a 32 unit slot between the crossbar and the bar. One evenodd path: an outer loop plus three holes (the cap, the left counter, the lower right quadrant).',
    use: 'At 16px it reads as a T inside a G ring with a 2px mouth tucked under the crossbar; the cap vanishes, so it is a monogram at small sizes and a globe from 32px up. The weakest letter read of the earlier round: the G depends on the mouth, and the arms of the T merge into the ring.',
  }),
];

/** The family record for a mark. */
export function markFamily(mark: Mark): { id: MarkFamily; label: string; principle: string } {
  return MARK_FAMILIES.find((family) => family.id === mark.family) ?? MARK_FAMILIES[0];
}

/**
 * The current mark, the doubled-line GT monogram, as the deck draws it
 * (deck/parts/head.html, the #gt-mark symbol): the reference the marks
 * are measured against, shown once at the end of /marks and never as a
 * candidate. One evenodd path in currentColor.
 */
export const REFERENCE_MARK = {
  name: 'The current mark',
  viewBox: '-8 214 1213 771',
  d: 'M363 222.5L1197 222.5L1196.5 283L834 283.5L832.5 976L773 975.5L772.5 398L359.5 398L341.5 401L301.5 414L271.5 430L249.5 446L231 463.5L214 484.5L190 529.5L180 567.5L178 613.5L185 653.5L196 682.5L217 717.5L242.5 746L270.5 768L314.5 790L342.5 798L372.5 802L399.5 802L430.5 798L475.5 783L502.5 768L524 751.5L523.5 747L415.5 748L414.5 684L583 684.5L583 923.5L580.5 926L516.5 955L476.5 967L439.5 974L403.5 977L355.5 976L326.5 973L287.5 965L252.5 954L221.5 941L187.5 923L155.5 902L121.5 874L97 849.5L77 825.5L55 793.5L33 752.5L15 705.5L4 656.5L0 613.5L2 556.5L10 511.5L23 469.5L44 423.5L66 387.5L99 346.5L129.5 317L170.5 286L225.5 256L275.5 237L325.5 226L363 222.5Z M386.5 282L322.5 288L275.5 301L220.5 327L167.5 365L123 413.5L103 443.5L87 474.5L71 518.5L61 578.5L63 641.5L68 669.5L78 703.5L107 762.5L143 810.5L171.5 838L194.5 856L248.5 887L305.5 907L366.5 916L403.5 916L442.5 912L490.5 900L523.5 887L524 826.5L479.5 847L440.5 858L399.5 863L344.5 860L291.5 846L254.5 829L214.5 802L186 775.5L165 749.5L141 708.5L125 664.5L118 624.5L118 573.5L126 530.5L139 494.5L165 449.5L201.5 408L238.5 379L292.5 352L341.5 339L373.5 336L773 336.5L772.5 283L386.5 282Z M888 337.5L1197 337.5L1196.5 398L949 398.5L948.5 976L888 975.5L888 337.5Z M415 571.5L692 572.5L692 830.5L668 858.5L633.5 890L631 890.5L631 635.5L414.5 635L415 571.5Z',
} as const;
