/* Generated by scripts/build-motion.mjs (pnpm build:motion) from motion/MOTION.md's
   roster ("## The films") and the translation series' motion/films/<slug>/BRIEF.md.
   Do not edit by hand. motion/ is untracked; this file and public/motion/ (the
   packages, and the published cuts' credits, sheets and scripts under the version
   rule pinned in public/motion/published.json) are what the site reads, so it builds
   without motion/. Statuses are read from the files when the script runs: rerun it
   after a render lands. */

export type MotionStatus = 'rendered' | 'in-production' | 'planned';
export type MotionSectionId = 'motion-films' | 'motion-series';
export type PackageSectionId = 'script' | 'post' | 'vocabulary' | 'sources' | 'checks';

/** A published render under public/media: root paths the page can play. */
export type MotionMedia = { video: string; poster: string };

/** Repository-relative paths that existed in motion/ at build time. Display only; never served. */
export type MotionLocal = { folder?: string; video?: string; poster?: string; sheet?: string; draft?: string };

/** One of the five sections of a research package, with a note read from its contents. */
export type PackageSection = { id: PackageSectionId; n: string; title: string; note: string };

/**
 * The published cut as public/motion/published.json pins it: its label (absent for a cut
 * made before the scripts), its length, and the repository-relative path of its final
 * render when a folder in motion/out holds it (display only; never served).
 */
export type MotionCut = { label?: string; length: string; render?: string };

/**
 * The published cut's contact sheet (two frames a second from frame 0, eight to a row):
 * the WebP the page shows, its pixel size and bytes, the frames it holds when its grid
 * is the kit's, and the full-resolution PNG when it is published.
 */
export type MotionSheet = { src: string; width: number; height: number; bytes: number; frames?: number; png?: string; pngBytes?: number };

/** The published cut's script as built: the copy served at src, the label, length and voices of its second line, and its count of lines. */
export type MotionScript = { src: string; label?: string; length: string; voices: string; lines: number };

/** A newer cut in motion/out, in review and not published: its label when its own script names it, and its length. Nothing else of it reaches the site. */
export type MotionReview = { label?: string; length: string };

export type MotionPackage = {
  /** the package h1 as plain text (asterisks stripped) */
  title: string;
  /** the series line under the h1, inline markdown */
  series: string;
  /** the word before " series": `Chinese`, `Hebrew` */
  seriesName: string;
  sections: readonly PackageSection[];
};

export type MotionFilm = {
  /** the roster slug; also /motion/<slug> for a film with a package */
  slug: string;
  /** `film-<slug>`: the shell item id and the row anchor on /motion */
  id: string;
  /** '01' to '12' in page order */
  n: string;
  /** the roster title, first letter capitalized; an entry without one takes its slug */
  title: string;
  /** the planned length from the roster: `45 to 50 s` */
  length: string;
  /** a roster parenthetical that is not a length: `assembled last` */
  note?: string;
  /** the final render's running time, `1:40`, read with ffprobe when it was available */
  runtime?: string;
  status: MotionStatus;
  section: MotionSectionId;
  /** one sentence of inline markdown */
  summary: string;
  media?: MotionMedia;
  local?: MotionLocal;
  /** the blog post the film trails, when it is on this site */
  post?: string;
  /** a published film's credits, copied verbatim from the folder that holds its published cut and served at this root path */
  credits?: string;
  /** the published cut, for a film with a web copy */
  cut?: MotionCut;
  /** the published cut's contact sheet, when the Videos session made one */
  sheet?: MotionSheet;
  /** the published cut's script as built, when the Videos session made one */
  script?: MotionScript;
  /** the cut in motion/out when it is not the published one */
  review?: MotionReview;
  pkg?: MotionPackage;
};

/** The two sections of /motion in page order, with their labels and leads. */
export const MOTION_SECTIONS: readonly { id: MotionSectionId; label: string; lead: string }[] = [
  { id: 'motion-films', label: 'Films', lead: 'The brand film, the mark sting, the blog films, the Lottie film, the release board and the showreel, in the order of the roster.' },
  { id: 'motion-series', label: 'Translation series', lead: 'Three films about how a translation made the words a language uses. Each one has a research package with a script, a post, a vocabulary table, sources and a fact-check list.' },
];

/** Where the generator writes each package body, relative to the repository root; the file is served at /motion/<slug>.md. */
export const MOTION_BODY_DIR = 'public/motion';

/** Every film on the roster, in page order. */
export const MOTION_FILMS: readonly MotionFilm[] = [
  {
    slug: 'brand-film',
    id: 'film-brand-film',
    n: '01',
    title: 'Every product in every language',
    length: '45 to 50 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'The company in one breath.',
  },
  {
    slug: 'mark-sting',
    id: 'film-mark-sting',
    n: '02',
    title: 'The bar monogram sting',
    length: '6 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'A logo sting for the start and end of any video.',
  },
  {
    slug: 'blog-designing-docs',
    id: 'film-blog-designing-docs',
    n: '03',
    title: 'Designing docs for humans',
    length: '20 to 24 s',
    runtime: '0:43',
    status: 'rendered',
    section: 'motion-films',
    summary: 'The post takes a docs page apart (zones, layers, the reading path, the redline pass, type, alignment, icons, the hit list).',
    media: {
      video: '/media/designing-docs-film.mp4',
      poster: '/media/designing-docs-poster.jpg',
    },
    local: {
      folder: 'motion/films/blog-designing-docs',
      video: 'motion/out/blog-designing-docs.mp4',
      poster: 'motion/out/blog-designing-docs.png',
      sheet: 'motion/out/_sheets/blog-designing-docs.png',
      draft: 'motion/out/_draft-blog-designing-docs.mp4',
    },
    post: '/blog/designing-docs-for-humans',
    cut: {
      label: 'round 7d revision without the frame',
      length: '42.5 s',
    },
    review: {
      label: 'v4',
      length: '53.5 s',
    },
  },
  {
    slug: 'blog-rewriting-docs',
    id: 'film-blog-rewriting-docs',
    n: '04',
    title: 'Rewriting docs for humans and agents',
    length: '20 to 24 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'Two readers of one page.',
    post: '/blog/rewriting-our-docs',
  },
  {
    slug: 'blog-fuma-nama',
    id: 'film-blog-fuma-nama',
    n: '05',
    title: 'Fuma Nama, the philosophy of an open-sourcerer',
    length: '20 to 24 s',
    runtime: '0:54',
    status: 'rendered',
    section: 'motion-films',
    summary: 'A portrait of Fumadocs\' creator and his credo.',
    media: {
      video: '/media/fuma-nama-film.mp4',
      poster: '/media/fuma-nama-poster.jpg',
    },
    local: {
      folder: 'motion/films/blog-fuma-nama',
      video: 'motion/out/blog-fuma-nama.mp4',
      poster: 'motion/out/blog-fuma-nama.png',
      sheet: 'motion/out/_sheets/blog-fuma-nama.png',
    },
    post: '/blog/fuma-nama',
    cut: {
      label: 'round 8',
      length: '54.0 s',
    },
    review: {
      label: 'v4',
      length: '59.5 s',
    },
  },
  {
    slug: 'blog-open-source',
    id: 'film-blog-open-source',
    n: '06',
    title: 'Supporting open-source software',
    length: '14 to 18 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'The grants announcement.',
  },
  {
    slug: 'lottie-translation',
    id: 'film-lottie-translation',
    n: '07',
    title: 'Translated Lottie animations',
    length: '18 to 22 s',
    status: 'in-production',
    section: 'motion-films',
    summary: 'For the upcoming post about translating Lottie animations.',
    local: {
      folder: 'motion/films/lottie-translation',
    },
  },
  {
    slug: 'release-board',
    id: 'film-release-board',
    n: '08',
    title: 'The release board',
    length: '14 to 18 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'The changelog as a split-flap departure board (a reference the brand names).',
  },
  {
    slug: 'showreel',
    id: 'film-showreel',
    n: '09',
    title: 'Showreel',
    length: '40 to 50 s',
    note: 'assembled last',
    status: 'planned',
    section: 'motion-films',
    summary: 'After every film is final, a 40 to 50 s showreel cut from them: the mark sting opens, the strongest four to six seconds of each film follow on hard cuts on the beat grid, the sting\'s end card closes.',
  },
  {
    slug: 'jihe-yuanben',
    id: 'film-jihe-yuanben',
    n: '10',
    title: 'Ricci, Xu Guangqi, and the Chinese vocabulary of Euclid',
    length: '60 to 100 s',
    runtime: '1:40',
    status: 'rendered',
    section: 'motion-series',
    summary: 'A Jesuit and a Hanlin Academy scholar sat down in Beijing to put Euclid into a language that had no word for "definition," "axiom," or "proof."',
    media: {
      video: '/media/jihe-yuanben-film.mp4',
      poster: '/media/jihe-yuanben-poster.jpg',
    },
    local: {
      folder: 'motion/films/jihe-yuanben',
      video: 'motion/out/jihe-yuanben.mp4',
      poster: 'motion/out/jihe-yuanben.png',
      sheet: 'motion/out/_sheets/jihe-yuanben.png',
      draft: 'motion/out/_draft-jihe-yuanben.mp4',
    },
    credits: '/motion/jihe-yuanben.credits.txt',
    cut: {
      label: '100 s cut',
      length: '100.0 s',
      render: 'motion/out/series-100s/jihe-yuanben.mp4',
    },
    sheet: {
      src: '/motion/sheets/jihe-yuanben.webp',
      width: 3093,
      height: 5472,
      bytes: 3065664,
      frames: 200,
      png: '/motion/sheets/jihe-yuanben.png',
      pngBytes: 17373573,
    },
    script: {
      src: '/motion/scripts/jihe-yuanben.md',
      label: '100 s cut',
      length: '100.0 s',
      voices: 'Narrator: Clara · Reader: Yun',
      lines: 25,
    },
    review: {
      label: 'v2',
      length: '74.8 s',
    },
    pkg: {
      title: 'Ricci, Xu Guangqi, and the Chinese vocabulary of Euclid',
      series: 'Chinese series, installment: *Jihe yuanben* 幾何原本, Beijing, 1607.',
      seriesName: 'Chinese',
      sections: [
        { id: 'script', n: '01', title: 'Animation script', note: 'About 85 seconds, 9 beats' },
        { id: 'post', n: '02', title: 'The post', note: '15 paragraphs' },
        { id: 'vocabulary', n: '03', title: 'Vocabulary table', note: '31 terms' },
        { id: 'sources', n: '04', title: 'Sources', note: '14 links' },
        { id: 'checks', n: '05', title: 'Fact-check list', note: '22 items' },
      ],
    },
  },
  {
    slug: 'journey-to-the-west',
    id: 'film-journey-to-the-west',
    n: '11',
    title: 'Waley, Hu Shih, and the English names of Journey to the West',
    length: '60 to 100 s',
    runtime: '1:40',
    status: 'rendered',
    section: 'motion-series',
    summary: 'In 1942 George Allen & Unwin in London published *Monkey*, Arthur Waley\'s translation of the Ming novel 西遊記 *Xiyou ji*, *Journey to the West*.',
    media: {
      video: '/media/journey-to-the-west-film.mp4',
      poster: '/media/journey-to-the-west-poster.jpg',
    },
    local: {
      folder: 'motion/films/journey-to-the-west',
      video: 'motion/out/journey-to-the-west.mp4',
      poster: 'motion/out/journey-to-the-west.png',
      sheet: 'motion/out/_sheets/journey-to-the-west.png',
    },
    credits: '/motion/journey-to-the-west.credits.txt',
    cut: {
      label: '100 s cut',
      length: '100.0 s',
      render: 'motion/out/series-100s/journey-to-the-west.mp4',
    },
    sheet: {
      src: '/motion/sheets/journey-to-the-west.webp',
      width: 3093,
      height: 5472,
      bytes: 1314862,
      frames: 200,
      png: '/motion/sheets/journey-to-the-west.png',
      pngBytes: 2162456,
    },
    script: {
      src: '/motion/scripts/journey-to-the-west.md',
      label: '100 s cut',
      length: '100.0 s',
      voices: 'Narrator: Clara · Reader: Yun',
      lines: 22,
    },
    review: {
      label: 'v2',
      length: '73.0 s',
    },
    pkg: {
      title: 'Waley, Hu Shih, and the English names of Journey to the West',
      series: 'Chinese series, installment: *Monkey*, London, 1942.',
      seriesName: 'Chinese',
      sections: [
        { id: 'script', n: '01', title: 'Animation script', note: 'About 85 seconds, 10 beats' },
        { id: 'post', n: '02', title: 'The post', note: '13 paragraphs' },
        { id: 'vocabulary', n: '03', title: 'Vocabulary table', note: '28 terms' },
        { id: 'sources', n: '04', title: 'Sources', note: '58 links' },
        { id: 'checks', n: '05', title: 'Fact-check list', note: '25 items' },
      ],
    },
  },
  {
    slug: 'modern-hebrew',
    id: 'film-modern-hebrew',
    n: '12',
    title: 'Ben-Yehuda, Pines, and the vocabulary of Modern Hebrew',
    length: '60 to 100 s',
    runtime: '1:40',
    status: 'rendered',
    section: 'motion-series',
    summary: 'In the autumn of 1881, Eliezer Ben-Yehuda (אליעזר בן־יהודה) and his wife Devora (דבורה) landed at Jaffa.',
    media: {
      video: '/media/modern-hebrew-film.mp4',
      poster: '/media/modern-hebrew-poster.jpg',
    },
    local: {
      folder: 'motion/films/modern-hebrew',
      video: 'motion/out/modern-hebrew.mp4',
      poster: 'motion/out/modern-hebrew.png',
      sheet: 'motion/out/_sheets/modern-hebrew.png',
    },
    credits: '/motion/modern-hebrew.credits.txt',
    cut: {
      label: '100 s cut',
      length: '100.0 s',
      render: 'motion/out/series-100s/modern-hebrew.mp4',
    },
    sheet: {
      src: '/motion/sheets/modern-hebrew.webp',
      width: 3093,
      height: 5472,
      bytes: 1255846,
      frames: 200,
      png: '/motion/sheets/modern-hebrew.png',
      pngBytes: 4375991,
    },
    script: {
      src: '/motion/scripts/modern-hebrew.md',
      label: '100 s cut',
      length: '100.0 s',
      voices: 'Narrator: Clara · Reader: Tomer',
      lines: 18,
    },
    review: {
      label: 'v2',
      length: '69.6 s',
    },
    pkg: {
      title: 'Ben-Yehuda, Pines, and the vocabulary of Modern Hebrew',
      series: 'Hebrew series, installment: *Milon ha-lashon ha-ivrit ha-yeshana ve-ha-hadasha* מלון הלשון העברית הישנה והחדשה, vol. 1, Jerusalem and Berlin, 1908.',
      seriesName: 'Hebrew',
      sections: [
        { id: 'script', n: '01', title: 'Animation script', note: 'About 88 seconds, 10 beats' },
        { id: 'post', n: '02', title: 'The post', note: '14 paragraphs' },
        { id: 'vocabulary', n: '03', title: 'Vocabulary table', note: '29 terms' },
        { id: 'sources', n: '04', title: 'Sources', note: '52 links' },
        { id: 'checks', n: '05', title: 'Fact-check list', note: '25 items' },
      ],
    },
  },
];

/** Each published script's story and spoken lines as plain text, by film slug: what the search matches a script on. */
export const MOTION_SCRIPT_WORDS: Readonly<Record<string, string>> = {
  'jihe-yuanben': 'In Beijing from 1606, Matteo Ricci translated Euclid by mouth and Xu Guangqi wrote it down in Chinese, and because only their six books of plane geometry circulated for 250 years, the word 幾何, which had meant “how much,” came to mean geometry. In 1606 two men in Beijing began to put Euclid into Chinese. Chinese had no words for definition, axiom or proof. The scholar Xu Guangqi read no Latin. The Jesuit Matteo Ricci had learned mathematics from Christopher Clavius. Ricci had tried once before in Shaozhou, around 1590. 言象之粗，而齟齬若是。 “This is only the coarse layer of words and figures, and still it grinds like this.” 泰西，利瑪竇，口譯。 Ricci translated by mouth. Ricci translated by mouth. 吳淞，徐光啓，筆受。 Xu received it with the brush. Xu received it with the brush. Chinese mathematics was written from problem to rule. In the Nine Chapters, each problem states a question, its answer and a procedure. In a commentary of 263 CE, Liu Hui justified the procedures by cutting figures apart and reassembling them. Euclid names each object first, and every theorem depends on the ones before it. A definition became 界說 an account of boundaries. 凡造論，先當分別解說論中所用名目，故曰界說。 “Whenever one builds an argument, one must first explain the names it uses; hence ‘boundary accounts’.” A, B and C are sounds, and a Chinese reader had no use for them. So they labelled the points with the Heavenly Stems. 甲、乙、丙、丁。 These are the first four Heavenly Stems. 幾何 was the ordinary word for “how much.” Ricci and Xu used it for magnitude. Only the six books of plane geometry circulated for 250 years, so the word narrowed to mean geometry.',
  'journey-to-the-west': 'Arthur Waley’s 1942 English translation of Journey to the West, a novel whose oldest surviving edition names no author, kept thirty of its hundred chapters and left out the meanings in its Chinese names, from the monkey’s surname to his stable title, and Julia Lovell’s translation of 2021 still uses Waley’s names. In 1942 a London publisher issued Monkey, Arthur Waley’s translation of Journey to the West. He kept thirty of its hundred chapters. Most scholars date the oldest surviving edition to 1592. It names no author. In 1923 Hu Shih argued for Wu Cheng’en, from a gazetteer entry that gives only a title. A patriarch makes the monkey’s surname from the word for macaque, 猢猻 macaque Without the animal radical, the second character leaves boy and infant, so his surname is 孫 Sun Richard and Waley both drop this analysis. The three disciples’ religious names share one character. 悟空、悟能、悟淨 Richard writes Seeker in all three, and Jenner writes Awakened. Waley calls them Monkey, Pigsy and Sandy. Heaven makes him 弼馬溫 a post in the imperial stables. The title is usually heard as ward off horse plague. None of these English titles keeps the pun. The chapter titles call him the mind-monkey, and give Monkey and Pig alchemical names. None of these names appears in Waley. Anthony Yu’s complete translation renders them all. Julia Lovell’s Monkey King of 2021 keeps Waley’s names.',
  'modern-hebrew': 'Eliezer Ben-Yehuda built new Hebrew words from old roots, and his dictionary of 1908 marks his accepted coinages, such as the word for bicycle, with a small sign, prints a different sign on electricity, leaves out Pines’s word for the tomato, which is the word Hebrew speakers use today, and names among its funders a society that was building a school in Haifa, whose board chose German for the sciences in 1913, nine years before the Mandate for Palestine named English, Arabic and Hebrew as the country’s official languages. In 1908 Eliezer Ben-Yehuda’s dictionary began to appear, promising many words that the author had created. In 1880 he rejected the phrase sefer milim as a copy of German Wörterbuch. From mila he made milon, the word for dictionary. A Hebrew noun is a root of consonants set into a pattern. He set the root for sling into the pattern of mafteakh and made makle’a, a cannon. מלים שחדשתי אני ושנתקבלו כבר בספרות של זמננו, או בדבור העברי בארץ ישראל. Words that I coined and that have already been accepted in the literature of our time, or in Hebrew speech in the Land of Israel. The dictionary prints this sign before the word for bicycle, ofnayim. The word for wheel is ofan. The ending for pairs turned it into ofnayim. The Greek translation renders Ezekiel’s khashmal as elektron. The poet Judah Leib Gordon followed it and used the word to mean electricity. The dictionary credits Gordon. Yehiel Michel Pines apparently coined agvaniya, the tomato. Ben-Yehuda found it immodest and kept it out of his dictionary. Pines’s word is in use. One of the book’s funders was building a technical school in Haifa. In 1913 the school’s board chose German for the sciences. By 1914 the school was to teach in Hebrew.',
};

/** The films with a research package, each a page at /motion/<slug>. */
export const MOTION_PACKAGE_SLUGS: readonly string[] = [
  'jihe-yuanben',
  'journey-to-the-west',
  'modern-hebrew',
];

const FILM_BY_SLUG: ReadonlyMap<string, MotionFilm> = new Map(MOTION_FILMS.map((film) => [film.slug, film]));

/** The film a slug names, or undefined for a slug that is not on the roster. */
export function getMotionFilm(slug: string): MotionFilm | undefined {
  return FILM_BY_SLUG.get(slug);
}

/** Where a film opens: its package page, or its row on /motion. */
export function motionHref(film: MotionFilm): string {
  return film.pkg ? `/motion/${film.slug}` : `/motion#${film.id}`;
}

export const MOTION_STATUS_LABEL: Readonly<Record<MotionStatus, string>> = {
  rendered: 'Rendered',
  'in-production': 'In production',
  planned: 'Planned',
};
