/* Generated by scripts/build-motion.mjs (pnpm build:motion) from motion/MOTION.md's
   roster ("## The films") and the translation series' motion/films/<slug>/BRIEF.md.
   Do not edit by hand. motion/ is untracked; this file and public/motion/ (the
   packages, and the published cuts' credits, sheets and scripts under the version
   rule pinned in public/motion/published.json) are what the site reads, so it builds
   without motion/. Statuses are read from the files when the script runs: rerun it
   after a render lands. */

export type MotionStatus = 'rendered' | 'in-production' | 'planned';
export type MotionSectionId = 'motion-films' | 'motion-series';
export type PackageSectionId = 'script' | 'post' | 'vocabulary' | 'sources' | 'checks';

/** A published render under public/media: root paths the page can play. */
export type MotionMedia = { video: string; poster: string };

/** Repository-relative paths that existed in motion/ at build time. Display only; never served. */
export type MotionLocal = { folder?: string; video?: string; poster?: string; sheet?: string; draft?: string };

/** One of the five sections of a research package, with a note read from its contents. */
export type PackageSection = { id: PackageSectionId; n: string; title: string; note: string };

/**
 * The published cut as public/motion/published.json pins it: its label (absent for a cut
 * made before the scripts), its length, and the repository-relative path of its final
 * render when a folder in motion/out holds it (display only; never served).
 */
export type MotionCut = { label?: string; length: string; render?: string };

/**
 * The published cut's contact sheet (two frames a second from frame 0, eight to a row):
 * the WebP the page shows, its pixel size and bytes, the frames it holds when its grid
 * is the kit's, and the full-resolution PNG when it is published.
 */
export type MotionSheet = { src: string; width: number; height: number; bytes: number; frames?: number; png?: string; pngBytes?: number };

/** The published cut's script as built: the copy served at src, the label, length and voices of its second line, and its count of lines. */
export type MotionScript = { src: string; label?: string; length: string; voices: string; lines: number };

/** A newer cut in motion/out, in review and not published: its label when its own script names it, and its length. Nothing else of it reaches the site. */
export type MotionReview = { label?: string; length: string };

export type MotionPackage = {
  /** the package h1 as plain text (asterisks stripped) */
  title: string;
  /** the series line under the h1, inline markdown */
  series: string;
  /** the word before " series": `Chinese`, `Hebrew` */
  seriesName: string;
  sections: readonly PackageSection[];
};

export type MotionFilm = {
  /** the roster slug; also /motion/<slug> for a film with a package */
  slug: string;
  /** `film-<slug>`: the shell item id and the row anchor on /motion */
  id: string;
  /** '01' to '12' in page order */
  n: string;
  /** the roster title, first letter capitalized; an entry without one takes its slug */
  title: string;
  /** the planned length from the roster: `45 to 50 s` */
  length: string;
  /** a roster parenthetical that is not a length: `assembled last` */
  note?: string;
  /** the final render's running time, `1:40`, read with ffprobe when it was available */
  runtime?: string;
  status: MotionStatus;
  section: MotionSectionId;
  /** one sentence of inline markdown */
  summary: string;
  media?: MotionMedia;
  local?: MotionLocal;
  /** the blog post the film trails, when it is on this site */
  post?: string;
  /** a published film's credits, copied verbatim from the folder that holds its published cut and served at this root path */
  credits?: string;
  /** the published cut, for a film with a web copy */
  cut?: MotionCut;
  /** the published cut's contact sheet, when the Videos session made one */
  sheet?: MotionSheet;
  /** the published cut's script as built, when the Videos session made one */
  script?: MotionScript;
  /** the cut in motion/out when it is not the published one */
  review?: MotionReview;
  pkg?: MotionPackage;
};

/** The two sections of /motion in page order, with their labels and leads. */
export const MOTION_SECTIONS: readonly { id: MotionSectionId; label: string; lead: string }[] = [
  { id: 'motion-films', label: 'Films', lead: 'The brand film, the mark sting, the blog films, the Lottie film, the release board and the showreel, in the order of the roster.' },
  { id: 'motion-series', label: 'Translation series', lead: 'Three films about how a translation made the words a language uses. Each one has a research package with a script, a post, a vocabulary table, sources and a fact-check list.' },
];

/** Where the generator writes each package body, relative to the repository root; the file is served at /motion/<slug>.md. */
export const MOTION_BODY_DIR = 'public/motion';

/** Every film on the roster, in page order. */
export const MOTION_FILMS: readonly MotionFilm[] = [
  {
    slug: 'brand-film',
    id: 'film-brand-film',
    n: '01',
    title: 'Every product in every language',
    length: '45 to 50 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'The company in one breath.',
  },
  {
    slug: 'mark-sting',
    id: 'film-mark-sting',
    n: '02',
    title: 'The bar monogram sting',
    length: '6 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'A logo sting for the start and end of any video.',
  },
  {
    slug: 'blog-designing-docs',
    id: 'film-blog-designing-docs',
    n: '03',
    title: 'Designing docs for humans',
    length: '50 to 55 s',
    runtime: '0:54',
    status: 'rendered',
    section: 'motion-films',
    summary: 'The post takes a docs page apart (zones, layers, the reading path, the redline pass, type, alignment, icons, the hit list).',
    media: {
      video: '/media/designing-docs-film.mp4',
      poster: '/media/designing-docs-poster.jpg',
    },
    local: {
      folder: 'motion/films/blog-designing-docs',
      video: 'motion/out/blog-designing-docs.mp4',
      poster: 'motion/out/blog-designing-docs.png',
      sheet: 'motion/out/_sheets/blog-designing-docs.png',
      draft: 'motion/out/_draft-blog-designing-docs.mp4',
    },
    post: '/blog/designing-docs-for-humans',
    cut: {
      label: 'v4',
      length: '53.5 s',
      render: 'motion/out/blog-designing-docs.mp4',
    },
    sheet: {
      src: '/motion/sheets/blog-designing-docs.webp',
      width: 3093,
      height: 3063,
      bytes: 1390160,
      frames: 107,
      png: '/motion/sheets/blog-designing-docs.png',
      pngBytes: 5977368,
    },
    script: {
      src: '/motion/scripts/blog-designing-docs.md',
      label: 'v4',
      length: '53.5 s',
      voices: 'Narrator: Frederick Surrey',
      lines: 11,
    },
  },
  {
    slug: 'blog-rewriting-docs',
    id: 'film-blog-rewriting-docs',
    n: '04',
    title: 'Rewriting docs for humans and agents',
    length: '20 to 24 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'Two readers of one page.',
    post: '/blog/rewriting-our-docs',
  },
  {
    slug: 'blog-fuma-nama',
    id: 'film-blog-fuma-nama',
    n: '05',
    title: 'Fuma Nama, the philosophy of an open-sourcerer',
    length: '55 to 60 s',
    runtime: '1:00',
    status: 'rendered',
    section: 'motion-films',
    summary: 'A portrait of Fumadocs\' creator and his credo.',
    media: {
      video: '/media/fuma-nama-film.mp4',
      poster: '/media/fuma-nama-poster.jpg',
    },
    local: {
      folder: 'motion/films/blog-fuma-nama',
      video: 'motion/out/blog-fuma-nama.mp4',
      poster: 'motion/out/blog-fuma-nama.png',
      sheet: 'motion/out/_sheets/blog-fuma-nama.png',
    },
    post: '/blog/fuma-nama',
    cut: {
      label: 'v4',
      length: '59.5 s',
      render: 'motion/out/blog-fuma-nama.mp4',
    },
    sheet: {
      src: '/motion/sheets/blog-fuma-nama.webp',
      width: 3093,
      height: 3282,
      bytes: 1213640,
      frames: 119,
      png: '/motion/sheets/blog-fuma-nama.png',
      pngBytes: 5263370,
    },
    script: {
      src: '/motion/scripts/blog-fuma-nama.md',
      label: 'v4',
      length: '59.5 s',
      voices: 'Narrator: Frederick Surrey',
      lines: 10,
    },
  },
  {
    slug: 'blog-open-source',
    id: 'film-blog-open-source',
    n: '06',
    title: 'Supporting open-source software',
    length: '14 to 18 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'The grants announcement.',
  },
  {
    slug: 'lottie-translation',
    id: 'film-lottie-translation',
    n: '07',
    title: 'Translated Lottie animations',
    length: '18 to 22 s',
    status: 'in-production',
    section: 'motion-films',
    summary: 'For the upcoming post about translating Lottie animations.',
    local: {
      folder: 'motion/films/lottie-translation',
    },
  },
  {
    slug: 'release-board',
    id: 'film-release-board',
    n: '08',
    title: 'The release board',
    length: '14 to 18 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'The changelog as a split-flap departure board (a reference the brand names).',
  },
  {
    slug: 'slash-announcement',
    id: 'film-slash-announcement',
    n: '09',
    title: 'Supporting Slash companies',
    length: '35 to 40 s',
    runtime: '0:36',
    status: 'rendered',
    section: 'motion-films',
    summary: 'The announcement of General Translation\'s partnership with Slash.',
    media: {
      video: '/media/slash-announcement-film.mp4',
      poster: '/media/slash-announcement-poster.jpg',
    },
    local: {
      folder: 'motion/films/slash-announcement',
      video: 'motion/out/slash-announcement.mp4',
      poster: 'motion/out/slash-announcement.png',
      sheet: 'motion/out/_sheets/slash-announcement.png',
    },
    credits: '/motion/slash-announcement.credits.txt',
    cut: {
      label: 'v8',
      length: '36.3 s',
      render: 'motion/out/slash-announcement.mp4',
    },
    sheet: {
      src: '/motion/sheets/slash-announcement.webp',
      width: 3093,
      height: 2187,
      bytes: 580072,
      frames: 73,
      png: '/motion/sheets/slash-announcement.png',
      pngBytes: 3177562,
    },
    script: {
      src: '/motion/scripts/slash-announcement.md',
      label: 'v8',
      length: '36.3 s',
      voices: 'Narrator: Frederick Surrey',
      lines: 6,
    },
  },
  {
    slug: 'gif-how-gt-works',
    id: 'film-gif-how-gt-works',
    n: '10',
    title: 'How General Translation works',
    length: '15 to 18 s',
    runtime: '0:17',
    status: 'rendered',
    section: 'motion-films',
    summary: 'A looping product GIF of how General Translation localizes an app, made for OpenAI for Startups: the app\'s text is wrapped in the T component, one command (npx gt translate) writes the translation files, a reviewer edits a translation in the Dashboard, and the app switches between English, Spanish, French and Japanese.',
    media: {
      video: '/media/how-gt-works-film.mp4',
      poster: '/media/how-gt-works-poster.jpg',
    },
    local: {
      folder: 'motion/films/gif-how-gt-works',
      video: 'motion/out/gif-how-gt-works.mp4',
      poster: 'motion/out/gif-how-gt-works.png',
      sheet: 'motion/out/_sheets/gif-how-gt-works.png',
    },
    cut: {
      length: '17.3 s',
      render: 'motion/out/gif-how-gt-works.mp4',
    },
    sheet: {
      src: '/motion/sheets/gif-how-gt-works.webp',
      width: 2319,
      height: 1311,
      bytes: 218848,
      frames: 35,
      png: '/motion/sheets/gif-how-gt-works.png',
      pngBytes: 406013,
    },
  },
  {
    slug: 'showreel',
    id: 'film-showreel',
    n: '11',
    title: 'Showreel',
    length: '40 to 50 s',
    note: 'assembled last',
    status: 'planned',
    section: 'motion-films',
    summary: 'After every film is final, a 40 to 50 s showreel cut from them: the mark sting opens, the strongest four to six seconds of each film follow on hard cuts on the beat grid, the sting\'s end card closes.',
  },
  {
    slug: 'jihe-yuanben',
    id: 'film-jihe-yuanben',
    n: '12',
    title: 'Ricci, Xu Guangqi, and the Chinese vocabulary of Euclid',
    length: '60 to 100 s',
    runtime: '1:15',
    status: 'rendered',
    section: 'motion-series',
    summary: 'A Jesuit and a Hanlin Academy scholar sat down in Beijing to put Euclid into a language that had no word for "definition," "axiom," or "proof."',
    media: {
      video: '/media/jihe-yuanben-film.mp4',
      poster: '/media/jihe-yuanben-poster.jpg',
    },
    local: {
      folder: 'motion/films/jihe-yuanben',
      video: 'motion/out/jihe-yuanben.mp4',
      poster: 'motion/out/jihe-yuanben.png',
      sheet: 'motion/out/_sheets/jihe-yuanben.png',
      draft: 'motion/out/_draft-jihe-yuanben.mp4',
    },
    credits: '/motion/jihe-yuanben.credits.txt',
    cut: {
      label: 'v2',
      length: '74.8 s',
      render: 'motion/out/jihe-yuanben.mp4',
    },
    sheet: {
      src: '/motion/sheets/jihe-yuanben.webp',
      width: 3093,
      height: 4158,
      bytes: 2199204,
      frames: 150,
      png: '/motion/sheets/jihe-yuanben.png',
      pngBytes: 12461090,
    },
    script: {
      src: '/motion/scripts/jihe-yuanben.md',
      label: 'v2',
      length: '74.8 s',
      voices: 'Narrator: Frederick Surrey · Reader: Yun',
      lines: 17,
    },
    pkg: {
      title: 'Ricci, Xu Guangqi, and the Chinese vocabulary of Euclid',
      series: 'Chinese series, installment: *Jihe yuanben* 幾何原本, Beijing, 1607.',
      seriesName: 'Chinese',
      sections: [
        { id: 'script', n: '01', title: 'Animation script', note: 'About 85 seconds, 9 beats' },
        { id: 'post', n: '02', title: 'The post', note: '15 paragraphs' },
        { id: 'vocabulary', n: '03', title: 'Vocabulary table', note: '31 terms' },
        { id: 'sources', n: '04', title: 'Sources', note: '14 links' },
        { id: 'checks', n: '05', title: 'Fact-check list', note: '22 items' },
      ],
    },
  },
  {
    slug: 'journey-to-the-west',
    id: 'film-journey-to-the-west',
    n: '13',
    title: 'Waley, Hu Shih, and the English names of Journey to the West',
    length: '60 to 100 s',
    runtime: '1:13',
    status: 'rendered',
    section: 'motion-series',
    summary: 'In 1942 George Allen & Unwin in London published *Monkey*, Arthur Waley\'s translation of the Ming novel 西遊記 *Xiyou ji*, *Journey to the West*.',
    media: {
      video: '/media/journey-to-the-west-film.mp4',
      poster: '/media/journey-to-the-west-poster.jpg',
    },
    local: {
      folder: 'motion/films/journey-to-the-west',
      video: 'motion/out/journey-to-the-west.mp4',
      poster: 'motion/out/journey-to-the-west.png',
      sheet: 'motion/out/_sheets/journey-to-the-west.png',
    },
    credits: '/motion/journey-to-the-west.credits.txt',
    cut: {
      label: 'v2',
      length: '73.0 s',
      render: 'motion/out/journey-to-the-west.mp4',
    },
    sheet: {
      src: '/motion/sheets/journey-to-the-west.webp',
      width: 3093,
      height: 4158,
      bytes: 883454,
      frames: 146,
      png: '/motion/sheets/journey-to-the-west.png',
      pngBytes: 1731909,
    },
    script: {
      src: '/motion/scripts/journey-to-the-west.md',
      label: 'v2',
      length: '73.0 s',
      voices: 'Narrator: Frederick Surrey · Reader: Yun',
      lines: 14,
    },
    pkg: {
      title: 'Waley, Hu Shih, and the English names of Journey to the West',
      series: 'Chinese series, installment: *Monkey*, London, 1942.',
      seriesName: 'Chinese',
      sections: [
        { id: 'script', n: '01', title: 'Animation script', note: 'About 85 seconds, 10 beats' },
        { id: 'post', n: '02', title: 'The post', note: '13 paragraphs' },
        { id: 'vocabulary', n: '03', title: 'Vocabulary table', note: '28 terms' },
        { id: 'sources', n: '04', title: 'Sources', note: '58 links' },
        { id: 'checks', n: '05', title: 'Fact-check list', note: '25 items' },
      ],
    },
  },
  {
    slug: 'modern-hebrew',
    id: 'film-modern-hebrew',
    n: '14',
    title: 'Ben-Yehuda, Pines, and the vocabulary of Modern Hebrew',
    length: '60 to 100 s',
    runtime: '1:10',
    status: 'rendered',
    section: 'motion-series',
    summary: 'In the autumn of 1881, Eliezer Ben-Yehuda (אליעזר בן־יהודה) and his wife Devora (דבורה) landed at Jaffa.',
    media: {
      video: '/media/modern-hebrew-film.mp4',
      poster: '/media/modern-hebrew-poster.jpg',
    },
    local: {
      folder: 'motion/films/modern-hebrew',
      video: 'motion/out/modern-hebrew.mp4',
      poster: 'motion/out/modern-hebrew.png',
      sheet: 'motion/out/_sheets/modern-hebrew.png',
    },
    credits: '/motion/modern-hebrew.credits.txt',
    cut: {
      label: 'v2',
      length: '69.6 s',
      render: 'motion/out/modern-hebrew.mp4',
    },
    sheet: {
      src: '/motion/sheets/modern-hebrew.webp',
      width: 3093,
      height: 3939,
      bytes: 580384,
      frames: 140,
      png: '/motion/sheets/modern-hebrew.png',
      pngBytes: 1571579,
    },
    script: {
      src: '/motion/scripts/modern-hebrew.md',
      label: 'v2',
      length: '69.6 s',
      voices: 'Narrator: Frederick Surrey',
      lines: 15,
    },
    pkg: {
      title: 'Ben-Yehuda, Pines, and the vocabulary of Modern Hebrew',
      series: 'Hebrew series, installment: *Milon ha-lashon ha-ivrit ha-yeshana ve-ha-hadasha* מלון הלשון העברית הישנה והחדשה, vol. 1, Jerusalem and Berlin, 1908.',
      seriesName: 'Hebrew',
      sections: [
        { id: 'script', n: '01', title: 'Animation script', note: 'About 88 seconds, 10 beats' },
        { id: 'post', n: '02', title: 'The post', note: '14 paragraphs' },
        { id: 'vocabulary', n: '03', title: 'Vocabulary table', note: '29 terms' },
        { id: 'sources', n: '04', title: 'Sources', note: '52 links' },
        { id: 'checks', n: '05', title: 'Fact-check list', note: '25 items' },
      ],
    },
  },
];

/** Each published script's story and spoken lines as plain text, by film slug: what the search matches a script on. */
export const MOTION_SCRIPT_WORDS: Readonly<Record<string, string>> = {
  'blog-designing-docs': 'Most docs readers are now AI agents, but humans still read docs to evaluate a product, so General Translation redesigned its docs from scratch around its writing: it deleted the clutter, made the sidebar one accordion, gave the writing open space, kept translated pages aligned and pointed each page at what its reader wants, and it still treats docs design as an open problem. Most docs readers are now AI agents. Humans still read docs to evaluate a product. General Translation redesigned its docs from scratch so people would read its writing. Interfaces keep getting more cluttered, which creates mental clutter. The redesign started by deleting extra lines, links, and buttons. The sidebar is now one accordion, which is rare among docs sites. The writing now has more open space around it. Translated pages keep the same spacing and alignment. Each page guides its reader toward the action they want. Docs design is an open problem, and the team keeps working on it.',
  'blog-fuma-nama': 'One developer, Fuma Nama, created Fumadocs, a docs framework with over 13,000 GitHub stars that Vercel Turborepo, shadcn/ui, Better Auth, Unkey and many others use, and he has built it for three years on top of his schoolwork. He learned to code by modding games and reading code, and he did not read documentation. He designed Fumadocs in four layers that developers can take apart, down to copying only the table of contents into their own code. He thinks he would build it the same shape again, and General Translation has made it its first open-source grantee. One developer created Fumadocs, a docs framework with over 13,000 stars on GitHub. Vercel Turborepo, shadcn/ui, Better Auth, Unkey and many others use it. Fuma Nama has built it for three years, on top of his schoolwork. He learned to code by modding games and reading piles of JavaScript. He did not look at any documentation while he was learning. He designed Fumadocs in four layers that developers can take apart and reshape. The CLI can copy just the table of contents into your codebase. If he started again from scratch, he thinks Fumadocs would probably have the same shape. Fumadocs is General Translation’s first open-source grantee.',
  'slash-announcement': 'Slash is building the financial command center for businesses and supports sending and receiving global payments to 180+ countries. General Translation is partnering with Slash, and eligible Slash customers can receive up to $2,000 in translation credits for their app, website, documentation, slides and design files. Slash is building the financial command center for businesses. They support sending and receiving global payments to over 180 countries. We\'re excited to partner with Slash to help ambitious companies reach customers in every language. So if you bank with Slash, we\'re giving you up to two thousand dollars in translation credits to localize any product surface. That covers your app, website, documentation, slides, design files, and more. Your product should exist in every language.',
  'jihe-yuanben': 'The Chinese word for geometry, 幾何, is often said to copy the sound of “geo.” In the 1607 Chinese Euclid it was the ordinary word for “how much.” Only six books of plane geometry existed in Chinese for 250 years, so the word for “how much” came to mean geometry. This title begins with the Chinese word for geometry. It is often said to copy the sound of geo. In 1606 two men in Beijing began to translate Euclid’s geometry. Only one of them could read Latin. 泰西，利瑪竇，口譯。 Matteo Ricci translated by mouth. 吳淞，徐光啓，筆受。 Xu Guangqi wrote it down with the brush. Chinese mathematics was written as questions, such as how large a field 15 paces by 16 is. That question ends with the title’s first two characters. A commentary written in 263 CE justified those methods by cutting figures apart and reassembling them. Euclid never asks a question, and he defines every object first. Chinese had no word for definition, so Ricci and Xu made one meaning “an account of boundaries.” A, B and C were only sounds, so they used a series every literate reader could recite. 甲、乙、丙、丁。 These are the first four Heavenly Stems. Those two characters were the ordinary word for “how much.” Ricci and Xu used them to mean quantity. For 250 years Chinese readers had only six of Euclid’s books, all on plane geometry. So the word for “how much” came to mean geometry.',
  'journey-to-the-west': 'The monkey hero’s surname is the word for macaque with its animal part taken off. The novel hides more monkeys in his stable title and calls him the mind-monkey. Arthur Waley’s 1942 English called him Monkey, and in 2021 that is still his English name. In the Chinese novel Journey to the West, the monkey hero’s surname comes from the word for macaque, with the animal part removed. Without the animal part, the second character leaves boy and infant, so his surname is Sun. In 1942 Arthur Waley’s English translation left this out, and a footnote translated Sun as Monkey. Waley called the book Monkey too. He kept thirty of the hundred chapters. In the novel, Heaven gives the monkey a post in the imperial stables. 弼馬溫 bìmǎwēn 避馬瘟 bìmǎwēn The title is usually heard as ward off horse plague. Chinese stables kept a macaque for that job. In the oldest surviving edition, the chapter titles call him the mind-monkey. The scholar Hu Shih introduced Waley’s book to Americans as humour and satire, freed from allegorical readings. Waley’s Monkey travels west with Pigsy the pig, Sandy the river monster and Tripitaka the monk. In 2021 Julia Lovell’s translation kept all four names, and its hero is still Monkey.',
  'modern-hebrew': 'For about seventeen centuries Hebrew was no one’s mother tongue. Eliezer Ben-Yehuda built new words from its own roots and marked his accepted coinages in his dictionary with a small sign. The tomato word he refused to print is the word Hebrew speakers use today. For about seventeen centuries, Hebrew was no one’s mother tongue. Jews read and wrote it, but many modern things had only phrases for names. Even a dictionary was called sefer milim, a copy of German Wörterbuch. In 1880 Eliezer Ben-Yehuda wrote that such copies had made Hebrew almost German. Instead he made milon from mila, which means word. The letter mem can mark a tool, so he put it before the root for sling and made makle’a, a cannon. In his own dictionary, this sign marks words he coined that people had already accepted. It stands before the bicycle, a word for two wheels modeled on the word for ears. No one is sure what the prophet Ezekiel meant by khashmal. An ancient Greek translation gave it as elektron, so a poet used it for electricity. Ben-Yehuda did not mark that word as his own. Yehiel Michel Pines apparently named the tomato agvaniya, from a root that means desire. Ben-Yehuda found the word immodest and kept it out of his dictionary. Today Hebrew speakers call the tomato by the word he kept out.',
};

/** The films with a research package, each a page at /motion/<slug>. */
export const MOTION_PACKAGE_SLUGS: readonly string[] = [
  'jihe-yuanben',
  'journey-to-the-west',
  'modern-hebrew',
];

const FILM_BY_SLUG: ReadonlyMap<string, MotionFilm> = new Map(MOTION_FILMS.map((film) => [film.slug, film]));

/** The film a slug names, or undefined for a slug that is not on the roster. */
export function getMotionFilm(slug: string): MotionFilm | undefined {
  return FILM_BY_SLUG.get(slug);
}

/** Where a film opens: its package page, or its row on /motion. */
export function motionHref(film: MotionFilm): string {
  return film.pkg ? `/motion/${film.slug}` : `/motion#${film.id}`;
}

export const MOTION_STATUS_LABEL: Readonly<Record<MotionStatus, string>> = {
  rendered: 'Rendered',
  'in-production': 'In production',
  planned: 'Planned',
};
