/* Generated by scripts/build-motion.mjs (pnpm build:motion) from motion/MOTION.md's
   roster ("## The films") and the translation series' motion/films/<slug>/BRIEF.md.
   Do not edit by hand. motion/ is untracked; this file and public/motion/<slug>.md
   are what the site reads, so it builds without motion/. Statuses are read from the
   files when the script runs: rerun it after a render lands. */

export type MotionStatus = 'rendered' | 'in-production' | 'planned';
export type MotionSectionId = 'motion-films' | 'motion-series';
export type PackageSectionId = 'script' | 'post' | 'vocabulary' | 'sources' | 'checks';

/** A published render under public/media: root paths the page can play. */
export type MotionMedia = { video: string; poster: string };

/** Repository-relative paths that existed in motion/ at build time. Display only; never served. */
export type MotionLocal = { folder?: string; video?: string; poster?: string; sheet?: string; draft?: string };

/** One of the five sections of a research package, with a note read from its contents. */
export type PackageSection = { id: PackageSectionId; n: string; title: string; note: string };

export type MotionPackage = {
  /** the package h1 as plain text (asterisks stripped) */
  title: string;
  /** the series line under the h1, inline markdown */
  series: string;
  /** the word before " series": `Chinese`, `Hebrew` */
  seriesName: string;
  sections: readonly PackageSection[];
};

export type MotionFilm = {
  /** the roster slug; also /motion/<slug> for a film with a package */
  slug: string;
  /** `film-<slug>`: the shell item id and the row anchor on /motion */
  id: string;
  /** '01' to '12' in page order */
  n: string;
  /** the roster title, first letter capitalized; an entry without one takes its slug */
  title: string;
  /** the planned length from the roster: `45 to 50 s` */
  length: string;
  /** a roster parenthetical that is not a length: `assembled last` */
  note?: string;
  /** the final render's running time, `1:40`, read with ffprobe when it was available */
  runtime?: string;
  status: MotionStatus;
  section: MotionSectionId;
  /** one sentence of inline markdown */
  summary: string;
  media?: MotionMedia;
  local?: MotionLocal;
  /** the blog post the film trails, when it is on this site */
  post?: string;
  /** a published film's credits, copied verbatim from motion/out/<slug>.credits.txt and served at this root path */
  credits?: string;
  pkg?: MotionPackage;
};

/** The two sections of /motion in page order, with their labels and leads. */
export const MOTION_SECTIONS: readonly { id: MotionSectionId; label: string; lead: string }[] = [
  { id: 'motion-films', label: 'Films', lead: 'The brand film, the mark sting, the blog films, the Lottie film, the release board and the showreel, in the order of the roster.' },
  { id: 'motion-series', label: 'Translation series', lead: 'Three films about how a translation made the words a language uses. Each one has a research package with a script, a post, a vocabulary table, sources and a fact-check list.' },
];

/** Where the generator writes each package body, relative to the repository root; the file is served at /motion/<slug>.md. */
export const MOTION_BODY_DIR = 'public/motion';

/** Every film on the roster, in page order. */
export const MOTION_FILMS: readonly MotionFilm[] = [
  {
    slug: 'brand-film',
    id: 'film-brand-film',
    n: '01',
    title: 'Every product in every language',
    length: '45 to 50 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'The company in one breath.',
  },
  {
    slug: 'mark-sting',
    id: 'film-mark-sting',
    n: '02',
    title: 'The bar monogram sting',
    length: '6 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'A logo sting for the start and end of any video.',
  },
  {
    slug: 'blog-designing-docs',
    id: 'film-blog-designing-docs',
    n: '03',
    title: 'Designing docs for humans',
    length: '20 to 24 s',
    runtime: '0:43',
    status: 'rendered',
    section: 'motion-films',
    summary: 'The post takes a docs page apart (zones, layers, the reading path, the redline pass, type, alignment, icons, the hit list).',
    media: {
      video: '/media/designing-docs-film.mp4',
      poster: '/media/designing-docs-poster.jpg',
    },
    local: {
      folder: 'motion/films/blog-designing-docs',
      video: 'motion/out/blog-designing-docs.mp4',
      poster: 'motion/out/blog-designing-docs.png',
      sheet: 'motion/out/_sheets/blog-designing-docs.png',
      draft: 'motion/out/_draft-blog-designing-docs.mp4',
    },
    post: '/blog/designing-docs-for-humans',
  },
  {
    slug: 'blog-rewriting-docs',
    id: 'film-blog-rewriting-docs',
    n: '04',
    title: 'Rewriting docs for humans and agents',
    length: '20 to 24 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'Two readers of one page.',
    post: '/blog/rewriting-our-docs',
  },
  {
    slug: 'blog-fuma-nama',
    id: 'film-blog-fuma-nama',
    n: '05',
    title: 'Fuma Nama, the philosophy of an open-sourcerer',
    length: '20 to 24 s',
    runtime: '0:54',
    status: 'rendered',
    section: 'motion-films',
    summary: 'A portrait of Fumadocs\' creator and his credo.',
    media: {
      video: '/media/fuma-nama-film.mp4',
      poster: '/media/fuma-nama-poster.jpg',
    },
    local: {
      folder: 'motion/films/blog-fuma-nama',
      video: 'motion/out/blog-fuma-nama.mp4',
      poster: 'motion/out/blog-fuma-nama.png',
      sheet: 'motion/out/_sheets/blog-fuma-nama.png',
    },
    post: '/blog/fuma-nama',
  },
  {
    slug: 'blog-open-source',
    id: 'film-blog-open-source',
    n: '06',
    title: 'Supporting open-source software',
    length: '14 to 18 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'The grants announcement.',
  },
  {
    slug: 'lottie-translation',
    id: 'film-lottie-translation',
    n: '07',
    title: 'Translated Lottie animations',
    length: '18 to 22 s',
    status: 'in-production',
    section: 'motion-films',
    summary: 'For the upcoming post about translating Lottie animations.',
    local: {
      folder: 'motion/films/lottie-translation',
    },
  },
  {
    slug: 'release-board',
    id: 'film-release-board',
    n: '08',
    title: 'The release board',
    length: '14 to 18 s',
    status: 'planned',
    section: 'motion-films',
    summary: 'The changelog as a split-flap departure board (a reference the brand names).',
  },
  {
    slug: 'showreel',
    id: 'film-showreel',
    n: '09',
    title: 'Showreel',
    length: '40 to 50 s',
    note: 'assembled last',
    status: 'planned',
    section: 'motion-films',
    summary: 'After every film is final, a 40 to 50 s showreel cut from them: the mark sting opens, the strongest four to six seconds of each film follow on hard cuts on the beat grid, the sting\'s end card closes.',
  },
  {
    slug: 'jihe-yuanben',
    id: 'film-jihe-yuanben',
    n: '10',
    title: 'Ricci, Xu Guangqi, and the Chinese vocabulary of Euclid',
    length: '60 to 100 s',
    runtime: '1:40',
    status: 'rendered',
    section: 'motion-series',
    summary: 'A Jesuit and a Hanlin Academy scholar sat down in Beijing to put Euclid into a language that had no word for "definition," "axiom," or "proof."',
    media: {
      video: '/media/jihe-yuanben-film.mp4',
      poster: '/media/jihe-yuanben-poster.jpg',
    },
    local: {
      folder: 'motion/films/jihe-yuanben',
      video: 'motion/out/jihe-yuanben.mp4',
      poster: 'motion/out/jihe-yuanben.png',
      sheet: 'motion/out/_sheets/jihe-yuanben.png',
      draft: 'motion/out/_draft-jihe-yuanben.mp4',
    },
    credits: '/motion/jihe-yuanben.credits.txt',
    pkg: {
      title: 'Ricci, Xu Guangqi, and the Chinese vocabulary of Euclid',
      series: 'Chinese series, installment: *Jihe yuanben* 幾何原本, Beijing, 1607.',
      seriesName: 'Chinese',
      sections: [
        { id: 'script', n: '01', title: 'Animation script', note: 'About 85 seconds, 9 beats' },
        { id: 'post', n: '02', title: 'The post', note: '15 paragraphs' },
        { id: 'vocabulary', n: '03', title: 'Vocabulary table', note: '31 terms' },
        { id: 'sources', n: '04', title: 'Sources', note: '14 links' },
        { id: 'checks', n: '05', title: 'Fact-check list', note: '22 items' },
      ],
    },
  },
  {
    slug: 'journey-to-the-west',
    id: 'film-journey-to-the-west',
    n: '11',
    title: 'Waley, Hu Shih, and the English names of Journey to the West',
    length: '60 to 100 s',
    runtime: '1:40',
    status: 'rendered',
    section: 'motion-series',
    summary: 'In 1942 George Allen & Unwin in London published *Monkey*, Arthur Waley\'s translation of the Ming novel 西遊記 *Xiyou ji*, *Journey to the West*.',
    media: {
      video: '/media/journey-to-the-west-film.mp4',
      poster: '/media/journey-to-the-west-poster.jpg',
    },
    local: {
      folder: 'motion/films/journey-to-the-west',
      video: 'motion/out/journey-to-the-west.mp4',
      poster: 'motion/out/journey-to-the-west.png',
      sheet: 'motion/out/_sheets/journey-to-the-west.png',
      draft: 'motion/out/_draft-journey-to-the-west.mp4',
    },
    credits: '/motion/journey-to-the-west.credits.txt',
    pkg: {
      title: 'Waley, Hu Shih, and the English names of Journey to the West',
      series: 'Chinese series, installment: *Monkey*, London, 1942.',
      seriesName: 'Chinese',
      sections: [
        { id: 'script', n: '01', title: 'Animation script', note: 'About 85 seconds, 10 beats' },
        { id: 'post', n: '02', title: 'The post', note: '13 paragraphs' },
        { id: 'vocabulary', n: '03', title: 'Vocabulary table', note: '28 terms' },
        { id: 'sources', n: '04', title: 'Sources', note: '58 links' },
        { id: 'checks', n: '05', title: 'Fact-check list', note: '25 items' },
      ],
    },
  },
  {
    slug: 'modern-hebrew',
    id: 'film-modern-hebrew',
    n: '12',
    title: 'Ben-Yehuda, Pines, and the vocabulary of Modern Hebrew',
    length: '60 to 100 s',
    runtime: '1:40',
    status: 'rendered',
    section: 'motion-series',
    summary: 'In the autumn of 1881, Eliezer Ben-Yehuda (אליעזר בן־יהודה) and his wife Devora (דבורה) landed at Jaffa.',
    media: {
      video: '/media/modern-hebrew-film.mp4',
      poster: '/media/modern-hebrew-poster.jpg',
    },
    local: {
      folder: 'motion/films/modern-hebrew',
      video: 'motion/out/modern-hebrew.mp4',
      poster: 'motion/out/modern-hebrew.png',
      sheet: 'motion/out/_sheets/modern-hebrew.png',
      draft: 'motion/out/_draft-modern-hebrew.mp4',
    },
    credits: '/motion/modern-hebrew.credits.txt',
    pkg: {
      title: 'Ben-Yehuda, Pines, and the vocabulary of Modern Hebrew',
      series: 'Hebrew series, installment: *Milon ha-lashon ha-ivrit ha-yeshana ve-ha-hadasha* מלון הלשון העברית הישנה והחדשה, vol. 1, Jerusalem and Berlin, 1908.',
      seriesName: 'Hebrew',
      sections: [
        { id: 'script', n: '01', title: 'Animation script', note: 'About 88 seconds, 10 beats' },
        { id: 'post', n: '02', title: 'The post', note: '14 paragraphs' },
        { id: 'vocabulary', n: '03', title: 'Vocabulary table', note: '29 terms' },
        { id: 'sources', n: '04', title: 'Sources', note: '52 links' },
        { id: 'checks', n: '05', title: 'Fact-check list', note: '25 items' },
      ],
    },
  },
];

/** The films with a research package, each a page at /motion/<slug>. */
export const MOTION_PACKAGE_SLUGS: readonly string[] = [
  'jihe-yuanben',
  'journey-to-the-west',
  'modern-hebrew',
];

const FILM_BY_SLUG: ReadonlyMap<string, MotionFilm> = new Map(MOTION_FILMS.map((film) => [film.slug, film]));

/** The film a slug names, or undefined for a slug that is not on the roster. */
export function getMotionFilm(slug: string): MotionFilm | undefined {
  return FILM_BY_SLUG.get(slug);
}

/** Where a film opens: its package page, or its row on /motion. */
export function motionHref(film: MotionFilm): string {
  return film.pkg ? `/motion/${film.slug}` : `/motion#${film.id}`;
}

export const MOTION_STATUS_LABEL: Readonly<Record<MotionStatus, string>> = {
  rendered: 'Rendered',
  'in-production': 'In production',
  planned: 'Planned',
};
