/* Generated by scripts/build/skills.mjs (pnpm build:skills) from the curated
   skills in skills/<slug>/SKILL.md. Do not edit by hand: edit a SKILL.md and
   run the script; `pnpm lint:skills` fails while this file is stale. Sorted
   by the area each skill is filed under (its first), in SKILL_AREAS order,
   then by the script's reading order inside the area. The pages read each
   body and supporting file from skills/<slug>/ on the server. */

/** The areas a skill is filed under, in the order the site lists them. */
export type SkillArea = 'voice' | 'website' | 'landing' | 'aesthetic' | 'lints' | 'motion' | 'graphics' | 'videos' | 'diagrams' | 'isometry' | 'components' | 'workflow';

export type Skill = {
  /** the folder name under skills/: the slug of the page and of the raw files, and what the hash names */
  id: string;
  /** the frontmatter name; always the folder name */
  name: string;
  /** metadata.title: the page title and the row name */
  title: string;
  /** the frontmatter description, folded to one line: what the skill covers, then when to use it */
  description: string;
  /** metadata.areas; the first is the area the skill is filed under */
  areas: readonly SkillArea[];
  /** metadata.updated, YYYY-MM-DD */
  updated: string;
  /** the supporting files beside SKILL.md, relative to the folder: references, then scripts */
  files: readonly string[];
};

/** The areas in order, with their labels. */
export const SKILL_AREAS: readonly { id: SkillArea; label: string }[] = [
  { id: 'voice', label: 'Voice' },
  { id: 'website', label: 'Website' },
  { id: 'landing', label: 'Landing pages' },
  { id: 'aesthetic', label: 'Aesthetic' },
  { id: 'lints', label: 'Lints' },
  { id: 'motion', label: 'Motion' },
  { id: 'graphics', label: 'Graphics' },
  { id: 'videos', label: 'Videos' },
  { id: 'diagrams', label: 'Diagrams' },
  { id: 'isometry', label: 'Isometry' },
  { id: 'components', label: 'Components' },
  { id: 'workflow', label: 'Workflow' },
];

/** The folder the skills live in, relative to the repository root. */
export const SKILL_DIR = 'skills';

/** The page of one skill: `/skills/<slug>`. */
export function skillHref(slug: string): string {
  return `/skills/${slug}`;
}

/** One raw file of a skill as the site serves it: `/skills/<slug>/SKILL.md`, `/skills/<slug>/references/<file>`. */
export function skillFileHref(slug: string, file = 'SKILL.md'): string {
  return `/skills/${slug}/${file}`;
}

export const SKILLS: readonly Skill[] = [
  {
    id: 'gt-voice',
    name: 'gt-voice',
    title: 'Voice and the humanizer',
    description: 'How Kevin writes for General Translation: plain technical English for site copy, docs, decks, captions, films, UI strings, PR text and Slack; sentence shape; the heading and casing rules; writing for a stranger; the humanizer pass that strips AI patterns; code comments, commit messages and PR descriptions; and the first-person register for Kevin\'s own posts and reviews. Use when writing or editing any text Kevin will ship, publish or read, including code comments and PR descriptions, and before showing him a draft.',
    areas: ['voice'],
    updated: '2026-10-10',
    files: ['references/ai-patterns.md', 'references/before-after.md', 'references/launch-posts.md', 'references/messages.md', 'references/sources.md'],
  },
  {
    id: 'gt-website',
    name: 'gt-website',
    title: 'GT website',
    description: 'How generaltranslation.com is built and changed in gt-cloud\'s apps/landing: the app map, the engine CSS and the shared packages, translation in the site code, the Fumadocs docs and their agent-readable twins, the blog and its content submodule, the pages with rules of their own, crawlers, deploys and performance traps, the routing matrix, gt-next in other sites, and the checks before a pull request. Use when working on any page, doc, blog post, route or build of the GT website, together with gt-cloud\'s own gt-landing skill, which owns the file map.',
    areas: ['website'],
    updated: '2026-10-10',
    files: ['references/blog.md', 'references/deploys.md', 'references/docs.md', 'references/footer-and-theme.md', 'references/gt-next-integration.md', 'references/pages.md', 'references/routing-cases.txt', 'references/sources.md', 'scripts/routing-matrix.sh'],
  },
  {
    id: 'prototemplate',
    name: 'prototemplate',
    title: 'Working in Prototemplate',
    description: 'How to work in Prototemplate, Kevin\'s hub and wiki for General Translation work: what each route holds, the repository map, the viewer shell and its props, the registries that move together (surfaces, search index, docs, sitemap, llms.txt, captures), the chrome and sidebar rules, the book page standard, adding a page, a document, a handbook document or a skill, the build scripts, the shared checkout and its session lanes, the gates and landing, keeping the hub current with gt-cloud, and the curated skills with their contract and install. Use when changing anything in the Prototemplate repository, when adding a route, document or skill to it, or when building on it from another project.',
    areas: ['website', 'components'],
    updated: '2026-10-10',
    files: ['references/adding.md', 'references/build-scripts.md', 'references/chrome.md', 'references/hub.md', 'references/porting.md', 'references/registries.md', 'references/shell.md', 'references/skills.md', 'references/sources.md', 'scripts/check-registries.mjs'],
  },
  {
    id: 'gt-performance',
    name: 'gt-performance',
    title: 'Performance without visual loss',
    description: 'How General Translation keeps visual surfaces fast with no change to how they look: measure first with the machine\'s load recorded, 60 fps motion and no lag on first use, quality tiers driven by measured frame time, one WebGL context per engine and full cleanup on unmount, frozen previews in galleries, shader and module weight cut with a pixel-identity proof while the library API stays, Lighthouse on production builds, live values hydrated on static pages, and budgets that exit 1 on a breach. Use when a page or animation lags, before shipping a shader, canvas or heavy component, and when Kevin asks for Lighthouse or performance work.',
    areas: ['website', 'landing', 'motion'],
    updated: '2026-10-10',
    files: ['references/recipes.md', 'references/sources.md', 'references/webgl-lifecycles.md', 'scripts/frame-probe.mjs', 'scripts/pixel-diff.mjs'],
  },
  {
    id: 'gt-landing-pages',
    name: 'gt-landing-pages',
    title: 'Landing page grammar',
    description: 'The page grammar for General Translation landing and marketing pages: one rail, bands and hatch spacers, heads with a heading and one lead, the shared Cta with Title Case labels, the two icon tiers, Inter only, the mobile type ladder, the svh and dvh law, the read lines for scroll stories, and the rule that mock layouts and the toolchain prototypes are literal specs. Use when designing, building or reviewing a landing page, a home band, or a pricing, enterprise or careers page.',
    areas: ['landing', 'aesthetic'],
    updated: '2026-10-10',
    files: ['references/engine.md', 'references/material.md', 'references/rail-and-bands.md', 'references/scroll-stories.md', 'references/sources.md', 'references/type-on-the-page.md'],
  },
  {
    id: 'gt-aesthetic',
    name: 'gt-aesthetic',
    title: 'Taste and the review standard',
    description: 'Kevin\'s taste for General Translation work and the review he applies to it. The brand deck (deck/parts/head.html and DECK-GRAMMAR.md) is the reference for product surfaces and the shipped generaltranslation.com is the reference for the site. Covers contrast and hierarchy, the rhythm numbers, single lines whose weight carries meaning, one material per surface, type polish for heads and leads, the dated record of what Kevin rejected and why, and the review loop of one exemplar, a local review, then landing, with a script that measures a page\'s heads and leads. Use when designing or polishing any GT surface, when Kevin says something looks bad, busy or ugly, and before showing him design work.',
    areas: ['aesthetic', 'website', 'landing', 'components'],
    updated: '2026-10-10',
    files: ['references/measures.md', 'references/process.md', 'references/sources.md', 'references/verdicts.md', 'scripts/measure-type.mjs'],
  },
  {
    id: 'gt-brand',
    name: 'gt-brand',
    title: 'Brand and the correct Inter',
    description: 'The General Translation identity as rules: the name and the naming system, the four absolute colors and the one accent, the type system on the self-hosted rsms InterVariable 4.1 (weights, optical size, features, tracking, per-script fallbacks), the doubled-line GT monogram and the generated speed marks, language as material, the final avoid list, and what never appears on a public surface. Use before making anything that carries the GT brand (a page, a slide, a graphic, a film, an email or a social image), when choosing a face, weight, tracking or color, when placing a GT mark or a third-party logo, and when reviewing a surface against the brand.',
    areas: ['aesthetic'],
    updated: '2026-10-10',
    files: ['references/color.md', 'references/language.md', 'references/marks.md', 'references/sources.md', 'references/third-party.md', 'references/type.md'],
  },
  {
    id: 'gt-deck',
    name: 'gt-deck',
    title: 'Brand deck',
    description: 'How the General Translation brand deck in Prototemplate\'s deck/ folder is built and edited: the 1600 by 900 sheet, the Inter type sizes and color tokens, the layout classes, icons from the Heroicons 20 solid sprite, diagrams, openers and mood slides as artifact pictures, the speed mark slides, slide-scoped CSS, both themes, the build and shoot scripts, the registries a new slide touches, what counts as a defect, and how any GT presentation\'s story is written. Use when adding or editing a slide, rebuilding or checking the deck, reviewing a slide lane\'s work, writing another GT presentation, or borrowing the deck\'s grammar for another surface.',
    areas: ['aesthetic', 'graphics'],
    updated: '2026-10-10',
    files: ['references/borrowing.md', 'references/full-picture-slides.md', 'references/sources.md', 'references/type.md', 'references/viewer-and-build.md', 'references/writing.md', 'scripts/check-deck.mjs', 'scripts/heroicon-symbol.mjs'],
  },
  {
    id: 'gt-explorations',
    name: 'gt-explorations',
    title: 'Exploration rounds and convergence',
    description: 'How a General Translation design exploration runs from research to one landed design: reading Kevin\'s sources and measuring the reference sites, writing the page as text first, directions that differ in silhouette, material and action, one registry and one place to compare them live, in-page switches for effect variants, picks by Kevin\'s numbers, forks that never overwrite a version, critic composites against the reference, removing the losers and archiving retired versions, and keeping rounds local until he lands them. Use when Kevin asks for options, versions, variations, directions or "try N approaches", when he links a post or product to learn from, and when converging a design toward his pick.',
    areas: ['aesthetic', 'website', 'landing', 'graphics'],
    updated: '2026-10-10',
    files: ['references/charter.md', 'references/comparing.md', 'references/registry.md', 'references/rounds.md', 'references/sources.md', 'scripts/distinct-set.mjs'],
  },
  {
    id: 'gt-lints',
    name: 'gt-lints',
    title: 'Lints and gates',
    description: 'Every lint and gate that holds General Translation\'s design and copy rules, what each catches, where it runs and how to fix a failure: Prototemplate\'s line auditor, shell token lint, practices ratchet, picture lint, type lint, gt-ui oxlint copy, the public scan (lint:public), the copies manifest (lint:copies), the registries check (lint:registries), the tools index (lint:tools) and page check, and gt-cloud\'s oxlint plugins, email identity check and oxfmt. Also covers how a new rule becomes a lint and the gate hygiene that keeps a red gate from passing (chained gates, real exit codes, one browser gate at a time). Use before committing in either repository, when a lint or a build gate fails, or when Kevin asks for a new rule to be enforced.',
    areas: ['lints'],
    updated: '2026-10-10',
    files: ['references/gt-ui-rules.md', 'references/line-auditor.md', 'references/page-check.md', 'references/prototemplate-gates.md', 'references/sources.md'],
  },
  {
    id: 'gt-motion',
    name: 'gt-motion',
    title: 'Motion rules',
    description: 'The motion rules General Translation work follows on the web and in films: the eases and the 0.5 s beat grid, reading holds, the four allowed transitions, dithered fields that change only by a tone mix on one cell grid, the moving type law, loops created paused and played by scroll, reduced motion as a designed still, the engine lifecycle, scroll stories, and the traps in SVG dashes, GSAP and lottie-web. Use when animating anything for GT (a landing band, a diagram line, a dashboard or sign-in transition, a Lottie figure, a scroll story or a film scene) and when reviewing motion someone else built.',
    areas: ['motion', 'landing', 'videos', 'diagrams'],
    updated: '2026-10-10',
    files: ['references/recipes.md', 'references/sources.md', 'references/tools.md', 'references/traps.md', 'references/web.md'],
  },
  {
    id: 'gt-graphics',
    name: 'gt-graphics',
    title: 'Blog and brand graphics',
    description: 'How General Translation\'s blog and brand graphics are made with Prototemplate\'s graphics/ toolchain: product captures at 3 to 5x, labelled crops over glyphfield exports, the 26px text floor for the blog column, the audit and the render, contact sheets, stop-motion clips, webp and GIF export, the hand-off to a post, the GT docs measured for drawing, still artwork such as the partnership globes, marketplace listing screenshots, world maps, and the review standard for each. Use when illustrating a blog post, a launch or a feature with real product crops, when drawing the GT docs, or when making any still GT artwork or store listing.',
    areas: ['graphics'],
    updated: '2026-10-10',
    files: ['references/capture.md', 'references/docs-tokens.md', 'references/glyphfield-export.md', 'references/sources.md', 'references/still-artwork.md', 'references/stop-motion.md', 'references/traps.md'],
  },
  {
    id: 'gt-dither',
    name: 'gt-dither',
    title: 'Dither and artifact pictures',
    description: 'General Translation\'s 1-bit material and its artifact pictures: the 4x4 and 8x8 Bayer screens, coverage tiers that nest, the CPU engine (dither.ts) and the GPU studio field with its BAYER_PRESETS, the landing hero\'s bayer-8x8 field as the one material on product surfaces, Glyphfield as the authoring source for new shaders, and the Blue Marble standard for dithered photographs and scans with its cutter (pnpm mood-tone), its lint and its retired pictures. Use when adding a dithered field, picture, cover or texture to any GT surface, when choosing or tuning a studio preset, or when cutting, replacing, crediting or reviewing a mood picture in Prototemplate or gt-cloud.',
    areas: ['graphics', 'aesthetic'],
    updated: '2026-10-10',
    files: ['references/cutter.md', 'references/engines.md', 'references/glyphfield.md', 'references/pictures.md', 'references/sources.md'],
  },
  {
    id: 'gt-films',
    name: 'gt-films',
    title: 'Making a film',
    description: 'How General Translation films are made in Prototemplate\'s motion/ folder with HyperFrames: the brief, the research package, three directors and a judge for the script and the look, the storyboard, the kit, narration and music through ElevenLabs, the mix targets, draft and delivery renders, the frame-by-frame critic, and how a finished film reaches /motion; and the short media around a launch: promos, product demo videos, README GIFs, launch captures and briefs for the video vendor. Use when planning, scripting, building, critiquing or rendering a GT film, trailer, sting, showreel, promo or demo GIF, or when reviewing one against Kevin\'s standard.',
    areas: ['videos', 'motion'],
    updated: '2026-10-06',
    files: ['references/critic.md', 'references/pipeline.md', 'references/short-media.md', 'references/sound.md', 'references/traps.md', 'scripts/frames.mjs', 'scripts/measure-render.mjs', 'scripts/scan.mjs'],
  },
  {
    id: 'gt-diagrams',
    name: 'gt-diagrams',
    title: 'Drawing diagrams',
    description: 'How General Translation diagrams are drawn: when a diagram earns its place, the existing diagram components to mount first, inline SVG with ink, mid and hairline strokes, label sizes per surface, the doubled-line connector and its pulse, crossings and straight taps, theme-safe fills, and the check at 2x crops; and the isometric family: the 30 degree projection in iso.ts, light from the upper left, the extrusion recipe, one accent object, marks seated as alpha masks, the DitheredMark shimmer, the build and scan animations and the reference drawings such as the Locadex iso. Use when drawing a flow, an architecture, a stack, a before and after, a timeline or an isometric figure for a page, a slide, a post graphic or a film, or when reviewing a figure\'s junctions and labels.',
    areas: ['diagrams', 'isometry'],
    updated: '2026-10-10',
    files: ['references/checking.md', 'references/color.md', 'references/components.md', 'references/dashes.md', 'references/doubled-line.md', 'references/isometric-recipes.md', 'references/isometric.md', 'references/sources.md', 'scripts/deck-page.mjs', 'scripts/figure-check.mjs'],
  },
  {
    id: 'gt-components',
    name: 'gt-components',
    title: 'Components to reuse',
    description: 'The components General Translation work reuses before writing new ones: gt-cloud\'s packages/ui (header, footer, theme toggle, language selector, LocaleFlag, ScrollArea, Button), the landing\'s Cta and Bento primitives, the gt-ui design rules and the oxlint rules that hold them, the icon tiers, the React and translation rules, Prototemplate\'s instruments library (dither, studio field, glyph field, DoubledLine, EdgeGlobe, LocaleTag, RevealSeam, EverySentence) and its viewer shell, and when an outside library is the right call. Use when building or reviewing UI in gt-cloud or Prototemplate, or before adding a component.',
    areas: ['components', 'landing', 'website'],
    updated: '2026-10-10',
    files: ['references/behavior.md', 'references/icons.md', 'references/instruments.md', 'references/react.md', 'references/shared-ui.md', 'references/sources.md', 'references/viewer-shell.md'],
  },
  {
    id: 'gt-product-surfaces',
    name: 'gt-product-surfaces',
    title: 'Product surfaces',
    description: 'A map of General Translation\'s product surfaces (the sign-in plate and the auth pages, the four-step onboarding, the dashboard shell, plans and billing, the partner credit pages on the plate) to the skills that own their rules, and the state gallery method for reviewing a flow: every state reachable from one console, screenshots taken from it, and each new state added with the flow. It holds no rules of its own. Use when starting work on a GT product surface, to find which skill holds its rules, and before showing Kevin the states of a sign-in, onboarding or CLI login flow.',
    areas: ['components', 'aesthetic', 'workflow'],
    updated: '2026-10-10',
    files: ['references/sources.md'],
  },
  {
    id: 'gt-local-dev',
    name: 'gt-local-dev',
    title: 'Review servers and local environments',
    description: 'How General Translation apps run locally so Kevin can review and try them: the review servers and their ports (the gt-cloud landing on 3001, Prototemplate on 3005, the dashboard environment on 1355), the order of checks when he cannot see a change, the per-worktree dashboard dev environment with a seeded session, the /dev/states gallery and the Stripe stand-in, real providers only with his approval, a CLI login he can try without touching his credentials, and keeping servers current and few. Use when starting, restarting or debugging a local server for GT work, when Kevin asks to see or try something locally, or when setting up a new machine or worktree.',
    areas: ['workflow', 'website'],
    updated: '2026-10-10',
    files: ['references/sources.md'],
  },
  {
    id: 'gt-verify',
    name: 'gt-verify',
    title: 'Proving work is done',
    description: 'How to prove General Translation work is done before saying so: measure what renders at the spot Kevin flagged, run the real gesture and the real flow, walk the stress matrix for scroll stories and animated sections, cover the viewports, themes, browsers, accessibility and edge counts that check:pages misses, re-check what was already right, verify the live deployment, sweep the whole class of a defect, find the root cause and guard it, compare a whole page set before and after an upgrade, and report how each item was verified. Use before reporting any fix or feature as done, when Kevin says something is still broken, and when closing a round.',
    areas: ['workflow', 'lints', 'website', 'aesthetic', 'motion'],
    updated: '2026-10-10',
    files: ['references/cases.md', 'references/parity-review.md', 'references/recipes.md', 'references/sources.md', 'scripts/compare-signatures.py', 'scripts/page-signature.py', 'scripts/page-signature.test.py', 'scripts/probe.mjs', 'scripts/stress.mjs'],
  },
  {
    id: 'gt-ship',
    name: 'gt-ship',
    title: 'Branches, PRs and landing',
    description: 'How General Translation work moves from a worktree to main: one session per lane and one worktree per branch, the commit identity gt-cloud\'s deploys require, staging by explicit path, PR size discipline, the PR body with before and after crops, the review bots and required checks, Linear and reviewer requests, stacked PRs, the parity gate for onboarding and auth, and Prototemplate\'s rules for a shared checkout, local review and its Vercel deploys. Use when committing, opening, describing or updating a PR, answering Greptile or Bugbot, restacking after a merge, or landing work in gt-cloud or Prototemplate.',
    areas: ['workflow', 'lints'],
    updated: '2026-10-10',
    files: ['references/beyond-the-pr.md', 'references/pr-body.md', 'references/prototemplate.md', 'references/review-loop.md', 'references/sources.md', 'references/stacks.md', 'scripts/contact-sheet.py', 'scripts/contact-sheet.test.py', 'scripts/patch-body.py', 'scripts/patch-body.test.py', 'scripts/pr-assets.sh', 'scripts/pr-assets.test.sh', 'scripts/pr-bots.mjs', 'scripts/pr-size.mjs'],
  },
  {
    id: 'gt-reporting',
    name: 'gt-reporting',
    title: 'Reporting to Kevin',
    description: 'How to report to Kevin during and after General Translation work: show every result as crops, a running page, a gallery or files he can grab; state each item\'s exact ship state with its SHA, PR or URL; keep a numbered ledger of every ask; close a turn with what shipped, what only Kevin can do and numbered risks; draft the PR slate across gt-cloud, gt and content; batch decisions with recommendations; map his screenshot notes to fixes; and write one-sentence explanations, end-of-day recaps and stop-and-handover reports. Use when ending every turn that changed something, when Kevin asks "show me", "is it on main", "give me my PR list", "what did you do" or "what do you need from me", and when a round produces decisions for him.',
    areas: ['workflow', 'voice'],
    updated: '2026-10-10',
    files: ['references/examples.md', 'references/sources.md', 'scripts/pr-slate.mjs'],
  },
  {
    id: 'gt-orchestration',
    name: 'gt-orchestration',
    title: 'Running agent fleets and long autonomous runs',
    description: 'How General Translation work runs across many agents and over long autonomous runs: when to fan out and when to stay linear, the spec before a build fan-out, lanes that own files, lane prompts that open with Kevin\'s words, the self-contained brief for a subagent, a task chip or another session, critic-scored convergence against a named reference, adversarial verification of findings, keeping going and resuming dead agents, heartbeats and spend caps for paid model campaigns, corrective handoffs, and closing a round. Use when planning or running a workflow, spawning subagents or task chips, writing a brief or handoff for another agent, or resuming work after an interruption.',
    areas: ['workflow'],
    updated: '2026-10-10',
    files: ['references/briefs.md', 'references/campaigns.md', 'references/convergence.md', 'references/examples/critic-loop.js', 'references/examples/probe.js', 'references/examples/research.js', 'references/examples/write.js', 'references/handoffs.md', 'references/harness-traps.md', 'references/sources.md', 'references/workflow-shapes.md', 'scripts/replay-edits.py', 'scripts/replay-edits.test.py'],
  },
];

const SKILL_BY_SLUG: ReadonlyMap<string, Skill> = new Map(SKILLS.map((skill) => [skill.id, skill]));

/** The skill a slug names, or undefined for a slug that is not in the set. */
export function getSkill(slug: string): Skill | undefined {
  return SKILL_BY_SLUG.get(slug);
}

/** One area as the index, the search and the sitemap list it: the skills filed under it, in SKILLS order. */
export type SkillGroup = {
  id: SkillArea;
  label: string;
  /** skills.length, for a count next to the label */
  count: number;
  skills: readonly { slug: string; title: string; href: string }[];
};

/** The areas with the skills filed under them, in SKILL_AREAS order; an area with none is left out. */
export const SKILL_GROUPS: readonly SkillGroup[] = SKILL_AREAS.map((area) => {
  const skills = SKILLS.filter((skill) => skill.areas[0] === area.id).map((skill) => ({
    slug: skill.id,
    title: skill.title,
    href: skillHref(skill.id),
  }));
  return { id: area.id, label: area.label, count: skills.length, skills };
}).filter((group) => group.count > 0);
