// Generated by scripts/build/updated.mjs (pnpm build:updated). Do not edit.
//
// The day each page last changed: the last commit on HEAD that touched the
// page's own sources and content (the paths are listed in the script), or
// the day the file was generated while those paths held uncommitted work
// (commit null; the next run fills it in). Keys are route pathnames.
// pnpm lint:updated fails when this file is behind HEAD. Server modules
// only: a page passes its one entry to its viewer, and the check refuses a
// 'use client' module that imports this file.
import type { PageUpdated } from './page-updated';

export const UPDATED: Readonly<Record<string, PageUpdated>> = {
  '/brand': { day: '2026-10-10', at: '2026-10-10T08:23:59-07:00', commit: 'c14a965', src: 'd989157d' },
  '/docs': { day: '2026-10-10', at: '2026-10-10T10:59:11-07:00', commit: '5375a2c', src: '90684207' },
  '/handbook': { day: '2026-10-10', at: '2026-10-10T08:23:59-07:00', commit: 'd9d56c3', src: '2e348cde' },
  '/skills': { day: '2026-10-10', at: '2026-10-10', commit: null, src: '013673d4' },
  '/skills/gt-aesthetic': { day: '2026-10-10', at: '2026-10-10T08:29:26-07:00', commit: 'e59cc50', src: '1c4d5d1f' },
  '/skills/gt-brand': { day: '2026-10-10', at: '2026-10-10T08:49:57-07:00', commit: '86929d5', src: 'a18b54ed' },
  '/skills/gt-components': { day: '2026-10-10', at: '2026-10-10T08:29:26-07:00', commit: 'e59cc50', src: '8ede68fd' },
  '/skills/gt-deck': { day: '2026-10-10', at: '2026-10-10T08:49:57-07:00', commit: '86929d5', src: 'dd7f83a6' },
  '/skills/gt-diagrams': { day: '2026-10-10', at: '2026-10-10T08:29:25-07:00', commit: 'd1684b0', src: '9cbe2f8c' },
  '/skills/gt-dither': { day: '2026-10-10', at: '2026-10-10T08:29:26-07:00', commit: 'e59cc50', src: '4a680400' },
  '/skills/gt-explorations': { day: '2026-10-10', at: '2026-10-10T08:49:57-07:00', commit: '86929d5', src: 'd039b54e' },
  '/skills/gt-films': { day: '2026-10-10', at: '2026-10-10T09:06:15-07:00', commit: '5591541', src: '913f833a' },
  '/skills/gt-graphics': { day: '2026-10-10', at: '2026-10-10T08:29:26-07:00', commit: 'e59cc50', src: 'f6737f95' },
  '/skills/gt-landing-pages': { day: '2026-10-10', at: '2026-10-10T08:29:26-07:00', commit: 'e59cc50', src: 'b2aedf8e' },
  '/skills/gt-lints': { day: '2026-10-10', at: '2026-10-10T09:06:15-07:00', commit: '5591541', src: '0c6ddc4d' },
  '/skills/gt-local-dev': { day: '2026-10-10', at: '2026-10-10T10:59:07-07:00', commit: '3ea4c43', src: '281dc226' },
  '/skills/gt-motion': { day: '2026-10-10', at: '2026-10-10T08:29:26-07:00', commit: 'e59cc50', src: '87432f1b' },
  '/skills/gt-orchestration': { day: '2026-10-10', at: '2026-10-10T08:49:57-07:00', commit: '86929d5', src: 'cfa9f9fb' },
  '/skills/gt-performance': { day: '2026-10-10', at: '2026-10-10T08:29:52-07:00', commit: '644260e', src: 'bca98e3f' },
  '/skills/gt-product-surfaces': { day: '2026-10-10', at: '2026-10-10T08:29:25-07:00', commit: 'd1684b0', src: '839f7637' },
  '/skills/gt-reporting': { day: '2026-10-10', at: '2026-10-10T08:26:22-07:00', commit: '2a349e8', src: '403c9859' },
  '/skills/gt-ship': { day: '2026-10-10', at: '2026-10-10T08:29:43-07:00', commit: '5b00e13', src: '0e08e467' },
  '/skills/gt-verify': { day: '2026-10-10', at: '2026-10-10T10:59:11-07:00', commit: '5375a2c', src: 'cf591c55' },
  '/skills/gt-voice': { day: '2026-10-10', at: '2026-10-10T08:49:57-07:00', commit: '86929d5', src: '9a0192e3' },
  '/skills/gt-website': { day: '2026-10-10', at: '2026-10-10T10:59:07-07:00', commit: '0ee507d', src: '99644e97' },
  '/skills/prototemplate': { day: '2026-10-10', at: '2026-10-10T09:06:15-07:00', commit: '5591541', src: '9f87fa1b' },
  '/marks': { day: '2026-10-10', at: '2026-10-10T08:02:43-07:00', commit: '86fbdf6', src: '122d24f2' },
  '/blog': { day: '2026-10-10', at: '2026-10-10T08:23:59-07:00', commit: 'df207b7', src: '99b981b0' },
  '/graphics': { day: '2026-10-09', at: '2026-10-09T10:29:09-07:00', commit: '8f857fc', src: 'd0e23102' },
  '/motion': { day: '2026-10-10', at: '2026-10-10T08:02:44-07:00', commit: '25311fd', src: 'ec682ed6' },
  '/motion/jihe-yuanben': { day: '2026-10-10', at: '2026-10-10T08:02:43-07:00', commit: '86fbdf6', src: '7deaa67a' },
  '/motion/journey-to-the-west': { day: '2026-10-10', at: '2026-10-10T08:02:43-07:00', commit: '86fbdf6', src: 'f066292e' },
  '/motion/modern-hebrew': { day: '2026-10-10', at: '2026-10-10T08:02:43-07:00', commit: '86fbdf6', src: '10944d87' },
  '/directions/toolchain': { day: '2026-10-09', at: '2026-10-09T11:03:24-07:00', commit: '766f078', src: '075c2c85' },
  '/directions/chroma-flow': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '9ddb318b' },
  '/directions/dither-field': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '487d5a85' },
  '/directions/aurora-paper': { day: '2026-10-09', at: '2026-10-09T12:23:03-07:00', commit: '168eff2', src: '1a19bd6c' },
  '/directions/glyph-rain': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '6e5b1e2a' },
  '/directions/prism-light': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '24c77ef0' },
  '/directions/lens-gate': { day: '2026-10-09', at: '2026-10-09T12:23:03-07:00', commit: '168eff2', src: 'bc0f6ac7' },
  '/directions/paper-foundry': { day: '2026-10-09', at: '2026-10-09T12:23:03-07:00', commit: '168eff2', src: '0f8b15a3' },
  '/directions/terminus-board': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '54c173ff' },
  '/directions/wide-rule': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '3b2f37b7' },
  '/directions/event-horizon': { day: '2026-10-08', at: '2026-10-08T22:14:41-07:00', commit: '044dd65', src: '7be1516d' },
  '/directions/hourglass': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '1bad3e03' },
  '/directions/singularity': { day: '2026-10-09', at: '2026-10-09T12:23:03-07:00', commit: '168eff2', src: '127a66d5' },
  '/directions/singularity-dossier': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '4d1a12dd' },
  '/directions/singularity-orbit': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '41141006' },
  '/directions/singularity-signal': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '5dc2ed78' },
  '/directions/textile-block': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '7d219d82' },
  '/directions/stepped-fret': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: 'ab92b96b' },
  '/directions/glazed-bond': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '42a1109d' },
  '/directions/brick-lattice': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '031fcce0' },
  '/directions/screenfold-codex': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '2d624035' },
  '/directions/raking-relief': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '9b325166' },
  '/directions/calendar-rings': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: 'e160be39' },
  '/directions/talud-tablero': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: 'a920298b' },
  '/directions/apadana-grid': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: 'b365bc30' },
  '/directions/clay-tablet': { day: '2026-10-08', at: '2026-10-08T14:36:12-07:00', commit: 'b289851', src: '10ffbdc0' },
};

/** The entry for a route pathname; a route with a book head must have one. */
export function requireUpdated(pathname: string): PageUpdated {
  const entry = UPDATED[pathname];
  if (!entry) throw new Error(`${pathname} has no entry in src/lib/updated.ts; run pnpm build:updated`);
  return entry;
}
