#!/usr/bin/env python3
"""The 1592 contents for beat 1: eleven half pages and the 100 chapter columns.

The grid of ruled columns (right border x and pitch of each half page) and the
chapter-to-column map are the woodblock lane's (motion/concepts/
journey-to-the-west/woodblock/tools/grid.py, read only). The woodblock lane's
top and bottom values were the paper edge on some half pages, so its veils ran
past the foot of the pages. Here each column's own top and bottom printed
borders are measured inside the column, so a veil starts under the top border
and stops on the bottom border.

    python3 tools/contents.py      writes data/contents.js
"""
import json, os
import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# half page -> (right border x, pitch, first chapter in col 0); from woodblock/tools/grid.py
HALVES = {
    'p06L': (1530, 109.5, None),
    'p07R': (3050, 111.0, 10),
    'p07L': (1520, 111.0, 20),
    'p08R': (3055, 111.0, 30),
    'p08L': (1550, 110.5, 40),
    'p09R': (3010, 111.0, 50),
    'p09L': (1500, 110.5, 60),
    'p10R': (3031, 111.0, 70),
    'p10L': (1575, 111.0, 80),
    'p11R': (3044, 110.0, 90),
    'p11L': (1540, 110.0, 100),
}


def chapter_cols(key):
    R, P, n0 = HALVES[key]
    cols = {}
    if key == 'p06L':
        # col 0 title, col 1 月字卷之一, cols 2-6 ch 1-5, col 7 卷之二, cols 8-11 ch 6-9
        for i, ch in zip([2, 3, 4, 5, 6, 8, 9, 10, 11], range(1, 10)):
            cols[ch] = i
    elif key == 'p11L':
        cols[100] = 0
    else:
        cols[n0] = 0
        for k in range(5):
            cols[n0 + 1 + k] = 2 + k
        for k in range(4):
            cols[n0 + 6 + k] = 8 + k
    return {ch: (round(R - (i + 1) * P), round(R - i * P)) for ch, i in cols.items()}


def first_run(dk, a, b, step):
    """First run of rows darker than the threshold scanning from a towards b; returns (start, end)."""
    i = a
    while i != b:
        if dk[i] > 0.45:
            j = i
            while j != b and dk[j] > 0.25:
                j += step
            return (i, j) if step > 0 else (j, i)
        i += step
    return None


def main():
    out = {'halves': {}, 'chapters': {}}
    pages = {}
    for key, (R, P, n0) in HALVES.items():
        page = int(key[1:3])
        if page not in pages:
            pages[page] = np.asarray(Image.open(os.path.join(ROOT, 'assets', 'ncl', 'ncl08616-v01-p%02d.jpg' % page)).convert('L')).astype(float)
        im = pages[page]
        x0, x1 = round(R - 12 * P), R
        # The half page's own frame for the plate: the ruled block plus a margin of paper.
        dkb = (im[:, x0 + 20:x1 - 20] < 120).mean(axis=1)
        top = first_run(dkb, 520, 800, 1)
        bot = first_run(dkb, 2550, 2810, 1)
        out['halves'][key] = {'page': page, 'right': R, 'pitch': P, 'left': x0, 'top': top[0], 'bot': bot[1] if bot else 2700}
        for ch, (c0, c1) in chapter_cols(key).items():
            dk = (im[:, c0 + 8:c1 - 8] < 120).mean(axis=1)
            # The border inside this column, if it is where the half page's border is; otherwise the half page's.
            t = first_run(dk, max(540, top[0] - 40), top[0] + 40, 1)
            b = first_run(dk, 2560, 2810, 1)
            y0 = t[1] if t and abs(t[0] - top[0]) < 30 else top[1]
            y1 = b[0] if b and bot and abs(b[0] - bot[0]) < 40 else (bot[0] if bot else 2680)
            out['chapters'][str(ch)] = {'half': key, 'box': [c0 + 2, y0, c1 - 2, y1]}
    js = '/* Generated by tools/contents.py. The 1592 contents (NCL scan pp. 6 to 11): per half page, its ruled block; per chapter, its column box in scan pixels, from under the top border to the bottom border. */\nwindow.JW_CONTENTS = ' + json.dumps(out, separators=(',', ':')) + ';\n'
    with open(os.path.join(ROOT, 'data', 'contents.js'), 'w') as fh:
        fh.write(js)
    for k, h in out['halves'].items():
        print(k, h)
    print(len(out['chapters']), 'chapters')


if __name__ == '__main__':
    main()
