#!/usr/bin/env python3
"""Glyph outlines for the characters the film draws as paths.

After the names lane's tools/glyphs.py (motion/concepts/journey-to-the-west/
names/tools/glyphs.py). Reads Noto Serif CJK TC, the variable font the
jihe-yuanben film ships (read only, OFL 1.1), pins it to a weight, and writes
each character as separate closed contours in font units (y down, origin on
the baseline at the pen position, em box -880 to 120). In this face one
contour is very nearly one brush stroke, so a component of a character is a
set of contours (lib/jw.js SPLITS).

Two weights: 600 for the characters that are taken apart and set again (the
surname and the stable title), 500 for type registered on print and set on a
name card.

    python3 tools/glyphs.py        writes data/glyphs.js
"""
import json, os, sys
from fontTools.ttLib import TTFont
from fontTools.subset import Subsetter, Options
from fontTools.varLib import instancer
from fontTools.pens.recordingPen import DecomposingRecordingPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.areaPen import AreaPen

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, '..', 'jihe-yuanben', 'fonts', 'NotoSerifCJKtc-VF.otf')
SETS = {
    600: '猢猻胡孫子系弼馬溫避瘟',
    500: '西遊記吳承恩心猿金公木母',
}


def path_d(run):
    out = []
    f = lambda p: '%g,%g' % (round(p[0], 1), round(-p[1], 1))
    for op, args in run:
        if op == 'moveTo':
            out.append('M' + f(args[0]))
        elif op == 'lineTo':
            out.append('L' + f(args[0]))
        elif op == 'curveTo':
            out.append('C' + ' '.join(f(p) for p in args))
        elif op == 'qCurveTo':
            pts = list(args)
            on, offs = pts[-1], pts[:-1]
            for i, off in enumerate(offs):
                end = on if i == len(offs) - 1 else ((off[0] + offs[i + 1][0]) / 2, (off[1] + offs[i + 1][1]) / 2)
                out.append('Q%s %s' % (f(off), f(end)))
            if not offs:
                out.append('L' + f(on))
        elif op in ('closePath', 'endPath'):
            out.append('Z')
    return ''.join(out)


def contours(gs, name):
    pen = DecomposingRecordingPen(gs)
    gs[name].draw(pen)
    runs, cur = [], []
    for op, args in pen.value:
        cur.append((op, args))
        if op in ('closePath', 'endPath'):
            runs.append(cur)
            cur = []
    res = []
    for run in runs:
        ap, bp = AreaPen(), BoundsPen(None)
        for op, args in run:
            getattr(ap, op)(*args)
            getattr(bp, op)(*args)
        x0, y0, x1, y1 = bp.bounds
        res.append({'d': path_d(run), 'a': round(ap.value, 1), 'b': [round(x0, 1), round(-y1, 1), round(x1, 1), round(-y0, 1)]})
    return res


def build(weight, text):
    font = TTFont(SRC)
    opts = Options()
    opts.layout_features = ['*']
    sub = Subsetter(options=opts)
    sub.populate(text=text)
    sub.subset(font)
    font = instancer.instantiateVariableFont(font, {'wght': weight})
    cmap, gs = font.getBestCmap(), font.getGlyphSet()
    hm = font['hmtx']
    out = {}
    for ch in dict.fromkeys(text):
        name = cmap.get(ord(ch))
        if not name:
            print('missing', ch, file=sys.stderr)
            continue
        cs = contours(gs, name)
        out[ch] = {'adv': hm[name][0], 'c': cs}
        print(weight, ch, len(cs), 'contours')
    return out


def main():
    data = {'upm': 1000, 'asc': 880, 'desc': -120}
    for w, text in SETS.items():
        data['w%d' % w] = build(w, text)
    with open(os.path.join(ROOT, 'data', 'glyphs.js'), 'w') as fh:
        fh.write('/* Generated by tools/glyphs.py from Noto Serif CJK TC (OFL 1.1), weights 600 and 500. */\nwindow.JW_GLYPHS = ')
        json.dump(data, fh, ensure_ascii=False, separators=(',', ':'))
        fh.write(';\n')


if __name__ == '__main__':
    main()
