#!/usr/bin/env python3
"""The plates: the crop of each scan that the film shows, at the size it shows it.

Every file in assets/ncl, assets/nlc, assets/loc and assets/ia is the archive's
own pixels (assets/SOURCES.md). A plate here is a rectangular crop of one of
them, trimmed to the paper so the scanner bed never shows, resampled once
(Lanczos) to the exact size it is shown on the 1920 x 1080 stage, and saved as
JPEG (quality 93). The browser then draws every plate one image pixel to one
stage pixel: it never resamples a scan at draw time, so its filtering cannot
vary between renders. Nothing is retouched: the NCL seal and red line, the NLC
watermark and the Cornell plate edges stay as scanned. s is the plate's scale
in stage pixels per scan pixel, never above 1. data/plates.js records each
crop in scan pixels and its stage size, so lib/jw.js maps scan pixels to stage
pixels. The two plates the camera pushes (1.00 to 1.03) are drawn at most 3
percent above their baked size during the push.

    python3 tools/plates.py      writes assets/plates/*.jpg and data/plates.js
"""
import json, os, re
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
A = os.path.join(ROOT, 'assets')

RICHARD_S = 296 / 1160  # beat 8: each plate 296 px wide
CONTENTS_S = 0.168  # beat 1: the eleven half pages
PLATES = {
    # id: (scan, [x0, y0, x1, y1] in scan pixels, s)
    'title': ('ncl/ncl08616-v01-p12.jpg', [1195, 700, 1590, 2050], 0.8),
    'preface': ('ncl/ncl08616-v01-p02.jpg', [1620, 606, 3090, 2830], 0.45),
    'hushih': ('loc/hushih-1939-harris-ewing-loc2016876181.jpg', [1120, 860, 3220, 3660], 0.268),
    'gazetteer': ('nlc/nlc-huaian-fuzhi-1626-v7-p04.jpg', [1020, 50, 1560, 1520], 0.7),
    # The naming passage ends at stage y 912 (the row of least ink between the
    # 猻 box, whose foot is at y 890, and the credit band), so its credit has
    # paper of its own, as every other plate's has (fix round; it ran to 1640).
    'naming': ('ncl/ncl08616-v01-p25.jpg', [2300, 560, 3058, 1472], 1),
    'woodcut': ('ncl/ncl08616-v01-p51.jpg', [224, 520, 3090, 2740], 0.356),
    'ch4': ('ncl/ncl08616-v01-p52.jpg', [990, 700, 1430, 1580], 1),
    'ch14': ('ncl/ncl08616-v01-p07.jpg', [2130, 626, 2690, 1799], 0.75),
    'ch86': ('ncl/ncl08616-v01-p10.jpg', [322, 858, 882, 2031], 0.75),
    'r58': ('ia/richard-1913-cu31924074502034-n58-plate.jpg', [300, 300, 1460, 2220], RICHARD_S),
    'r234': ('ia/richard-1913-cu31924074502034-n234-plate.jpg', [222, 300, 1382, 2220], RICHARD_S),
    'r250': ('ia/richard-1913-cu31924074502034-n250-plate.jpg', [212, 282, 1372, 2202], RICHARD_S),
}


# The paper of each contents spread, inside the scanner bed (first and last paper column, measured
# where the mean of rows 25 to 75 percent of the page is lighter than 90).
PAPER_X = {6: (191, 3085), 7: (169, 3093), 8: (181, 3098), 9: (157, 3061), 10: (191, 3084), 11: (177, 3072)}


def contents_halves():
    s = open(os.path.join(ROOT, 'data', 'contents.js')).read()
    d = json.loads(s[s.index('{'):s.rindex('}') + 1])
    out = {}
    for key, h in d['halves'].items():
        lo, hi = PAPER_X[h['page']]
        x0 = max(h['left'] - 40, lo + 10)
        x1 = min(h['right'] + 40, hi - 10)
        out['c-' + key] = ('ncl/ncl08616-v01-p%02d.jpg' % h['page'], [x0, h['top'] - 50, x1, h['bot'] + 50], CONTENTS_S)
    return out


def main():
    os.makedirs(os.path.join(A, 'plates'), exist_ok=True)
    plates = dict(PLATES)
    plates.update(contents_halves())
    data = {}
    for pid, (src, crop, sc) in plates.items():
        assert 0 < sc <= 1, (pid, sc)
        im = Image.open(os.path.join(A, src))
        x0, y0, x1, y1 = crop
        assert 0 <= x0 < x1 <= im.size[0] and 0 <= y0 < y1 <= im.size[1], (pid, crop, im.size)
        c = im.crop((x0, y0, x1, y1))
        if c.mode not in ('RGB', 'L'):
            c = c.convert('RGB')
        w, h = round((x1 - x0) * sc), round((y1 - y0) * sc)
        if (w, h) != c.size:
            c = c.resize((w, h), Image.LANCZOS)
        out = os.path.join(A, 'plates', pid + '.jpg')
        c.save(out, quality=93, subsampling=0)
        data[pid] = {'src': 'assets/plates/' + pid + '.jpg', 'scan': 'assets/' + src, 'crop': crop, 's': sc, 'w': w, 'h': h}
        print(pid, crop, round(sc, 5), (w, h))
    with open(os.path.join(ROOT, 'data', 'plates.js'), 'w') as fh:
        fh.write('/* Generated by tools/plates.py: each plate, its scan, its crop in scan pixels, its scale s and its stage size w x h (the image file is that size). */\nwindow.JW_PLATES = ')
        json.dump(data, fh, separators=(',', ':'))
        fh.write(';\n')


if __name__ == '__main__':
    main()
