'use client';

import { SquarePen } from 'lucide-react';
import { useRef } from 'react';

import { useQuietReveal } from './reveal';

type CellState = 'approved' | 'review' | 'editing' | undefined;

type Cell = { text: string; state?: CellState };

/**
 * Every string in this grid exists in the product: the English column is the
 * gt next-ssg example's source, and es/ja/de come from its generated
 * public/_gt/{es,ja,de}.json files — never hand-written. The split-state row
 * (es approved, ja still in review) is the feature, per M10: review state is
 * scoped to entry AND locale.
 */
const ROWS: readonly { key: string; src: string; es: Cell; ja: Cell; de: Cell }[] = [
  {
    key: 'app/page.tsx:5',
    src: 'Get started by editing the page.tsx file.',
    es: { text: 'Para comenzar, edita el archivo page.tsx.', state: 'approved' },
    ja: { text: '開始するには、page.tsxファイルを編集してください。', state: 'approved' },
    de: { text: 'Um zu beginnen, bearbeiten Sie die Datei page.tsx.', state: 'approved' },
  },
  {
    key: 'app/page.tsx:9',
    src: 'Generated by create-next-app',
    es: { text: 'Generado con Create Next App', state: 'approved' },
    ja: { text: 'create-next-app によって生成されました', state: 'review' },
    de: { text: 'Erstellt mit Create Next App', state: 'approved' },
  },
  {
    key: 'app/page.tsx:14',
    src: 'Deploy now',
    es: { text: 'Deploy Now', state: 'review' },
    ja: { text: '今すぐデプロイ', state: 'approved' },
    de: { text: 'Jetzt bereitstellen', state: 'editing' },
  },
  {
    key: 'app/page.tsx:18',
    src: 'Documentation',
    es: { text: 'Documentation', state: 'approved' },
    ja: { text: 'ドキュメント', state: 'approved' },
    de: { text: 'Dokumentation', state: 'approved' },
  },
  {
    key: 'app/page.tsx:6',
    src: 'Looking for a starting point or more instructions? Head to Templates or the Learning center.',
    es: {
      text: '¿Buscas un punto de partida o más instrucciones? Dirígete a Templates o al centro de Learning.',
      state: 'approved',
    },
    ja: {
      text: '開始点や詳細な手順をお探しですか？テンプレートまたはラーニングセンターをご覧ください。',
      state: 'review',
    },
    de: {
      text: 'Suchen Sie nach einem Ausgangspunkt oder weiteren Anweisungen? Gehen Sie zu Templates oder zum Learning Center.',
      state: 'approved',
    },
  },
];

const STATE_LABEL: Record<Exclude<CellState, undefined | 'editing'>, string> = {
  approved: 'Approved',
  review: 'Needs review',
};

function TranslationCell({ cell }: { cell: Cell }) {
  if (cell.state === 'editing') {
    return (
      <div className='ap-cell'>
        <div className='ap-edit'>
          <span className='ap-edit-text'>
            {cell.text}
            <i className='ap-caret' aria-hidden />
          </span>
          <span className='ap-edit-acts'>
            <button className='tc-btn tc-btn-solid ap-save' type='button'>
              Save
            </button>
            <span className='ap-edit-hint'>esc to cancel</span>
          </span>
        </div>
      </div>
    );
  }
  return (
    <div className='ap-cell'>
      <p className='ap-cell-text'>{cell.text}</p>
      {cell.state ? (
        <span className='ap-state' data-state={cell.state}>
          {STATE_LABEL[cell.state]}
        </span>
      ) : null}
    </div>
  );
}

/**
 * M10/M22 — the translation editor as the page's first product surface: the
 * real grid, source beside every target locale, review state per entry and
 * per locale, one cell mid-edit, the ⌘K search half-open. No skeleton bars;
 * the strings are the proof.
 */
export default function Editor() {
  const root = useRef<HTMLElement>(null);
  useQuietReveal(root);

  return (
    <section className='tc-sec' id='editor' ref={root}>
      <div className='tc-head'>
        <SquarePen className='tc-head-icon' strokeWidth={1} aria-hidden />
        <h2 data-reveal>Every locale on one screen.</h2>
        <p data-reveal>
          Agents write the translations. You open one grid — the source beside every target locale —
          and touch only what needs a human.
        </p>
      </div>

      <div className='ap-ws-wrap' data-reveal>
        <div className='tc-mount'>
          <div className='tc-card'>
            {/* The workspace runs in its night register: the page's one big
                product surface is a toned panel, not marks on paper — the
                grid's strings are white ink on #101010, and the one cell
                mid-edit inverts back to paper, so "you edit" is literally the
                light moment of the surface. */}
            <div className='ap-ws is-night'>
              <div className='ap-ws-bar'>
                <div className='ap-ws-tabs' role='tablist' aria-label='Editor views'>
                  <button type='button' role='tab' aria-selected='false'>
                    Files
                  </button>
                  <button type='button' role='tab' aria-selected='true' data-on='true'>
                    Components
                  </button>
                </div>
                <div className='ap-ws-search'>
                  <span>page.tsx</span>
                  <kbd>⌘K</kbd>
                </div>
                <div className='ap-ws-locales'>
                  <span data-on='true'>es</span>
                  <span data-on='true'>ja</span>
                  <span data-on='true'>de</span>
                  <span>fr</span>
                  <span>zh</span>
                </div>
                <div className='ap-ws-acts'>
                  <span>History</span>
                  <span>Download</span>
                </div>
              </div>

              <div className='ap-grid'>
                <div className='ap-grid-head'>
                  <span>Source</span>
                  <span>es</span>
                  <span>ja</span>
                  <span>de</span>
                </div>

                {ROWS.map((row) => (
                  <div className='ap-grid-row' key={row.key}>
                    <div className='ap-cell is-src'>
                      <p className='ap-cell-text'>{row.src}</p>
                      <span className='ap-cell-key'>{row.key}</span>
                    </div>
                    <TranslationCell cell={row.es} />
                    <TranslationCell cell={row.ja} />
                    <TranslationCell cell={row.de} />
                  </div>
                ))}

                {/* The ⌘K palette, half-open over the grid: a scrim dims the
                    rows behind it the way the real overlay does, so at any
                    scale this reads as a composed UI moment rather than a
                    panel stuck over content. */}
                <div className='ap-k-scrim' aria-hidden />
                <div className='ap-k' aria-hidden>
                  <div className='ap-k-input'>
                    <span>page.tsx</span>
                    <i className='ap-caret' />
                  </div>
                  <div className='ap-k-row'>
                    <span>Get started by editing the page.tsx file.</span>
                    <b>app/page.tsx:5</b>
                  </div>
                  <div className='ap-k-row'>
                    <span>Generated by create-next-app</span>
                    <b>app/page.tsx:9</b>
                  </div>
                  <div className='ap-k-row'>
                    <span>Deploy now</span>
                    <b>app/page.tsx:14</b>
                  </div>
                </div>
              </div>

              <div className='ap-ws-foot'>
                <span>Search by file name, component name, key, source text or translated text — ⌘K</span>
                <span>Annotations are not on the Starter plan</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
