'use client';

import { Stamp } from 'lucide-react';
import { useRef } from 'react';

import ReviewWorkspace from './ReviewWorkspace';
import { useQuietReveal } from './reveal';

/**
 * The regeneration diff — what "see diffs when translations are regenerated"
 * actually looks like: the flat public/_gt/ja.json ledger, one entry rewritten,
 * its neighbours as context. The two gutter marks are the direction's two
 * threads: one leaves as the removed line, one returns as the added line.
 */
const DIFF: readonly { d?: '-' | '+'; text: string }[] = [
  { text: '@@ public/_gt/ja.json @@' },
  { text: '"0d5c1f2a": "ドキュメント",' },
  { d: '-', text: '"a41f0c92": "create-next-app によって生成されました",' },
  { d: '+', text: '"a41f0c92": "create-next-app により生成されました",' },
  { text: '"3b9e51b7": "今すぐデプロイ",' },
  { text: '"8f2ab41c": "開始するには、page.tsxファイルを編集してください。",' },
  { text: '"6c2d84e0": "テンプレートまたはラーニングセンターをご覧ください。"' },
];

/**
 * M23/M24 — the review flow behind the grid: one entry expanded with its
 * labels, note and comment thread, and the version history the CLI writes
 * with `--tag`. State is carried by type weight and hairlines only — no
 * colored pills anywhere on this page.
 */
export default function ReviewFlow() {
  const root = useRef<HTMLElement>(null);
  useQuietReveal(root);

  return (
    <section className='tc-sec' id='review' ref={root}>
      <div className='tc-head'>
        <Stamp className='tc-head-icon' strokeWidth={1} aria-hidden />
        <h2 data-reveal>Agents write. You approve.</h2>
        <p data-reveal>
          Review state is scoped per entry and per locale — approve the Spanish translation while the
          Japanese one is still in review.
        </p>
      </div>

      {/* The typing workspace (toolchain's founder-batch review primitive),
          integrated as this section's live surface: agents writing, stamps
          settling — then the fork's own diff and review card detail it. */}
      <div className='ap-ws-wrap'>
        <ReviewWorkspace />
      </div>

      <div className='tc-row is-split'>
        <div className='tc-cell is-tall' data-reveal>
          <h3>Review, without living in a CAT tool</h3>
          <p>
            You review exceptions, not everything — the same content is simultaneously in your repo.
          </p>
          <ul className='tc-list'>
            <li>Every entry shows its source and all five targets at once</li>
            <li>Regenerated translations arrive as diffs, never as surprises</li>
            <li>Change a live string and the CDN serves it — no redeploy</li>
            <li>Labels, notes and threaded comments, scoped per locale</li>
          </ul>

          <div className='ap-diff' data-reveal>
            <div className='ap-diff-bar'>
              <span>$ npx gt translate — 1 entry regenerated</span>
              <span>ja</span>
            </div>
            <pre>
              {DIFF.map((line, i) => (
                <div className='ap-diff-line' data-d={line.d} key={i}>
                  <span className='ap-diff-g'>{line.d ?? ' '}</span>
                  {line.text}
                </div>
              ))}
            </pre>
          </div>
        </div>

        <div className='tc-cell is-tall is-framed' data-reveal>
          <div className='tc-card'>
            <div className='ap-rev'>
              <div className='ap-rev-head'>
                <p className='ap-rev-src'>Generated by create-next-app</p>
                <span className='ap-rev-loc'>ja</span>
              </div>
              <p className='ap-rev-tr' lang='ja'>
                create-next-app によって生成されました
              </p>

              <div className='ap-rev-labels'>
                <span>Needs review</span>
                <span>Legal</span>
              </div>

              <div className='ap-rev-note'>
                <b>Note</b>
                <span>Hold until the JP terms page ships.</span>
              </div>

              <div className='ap-rev-thread'>
                <div className='ap-rev-msg'>
                  <b>you</b>
                  <span>Is 生成されました the right register for the footer?</span>
                </div>
                <div className='ap-rev-msg'>
                  <b>locadex · agent</b>
                  <span>Matched the app&rsquo;s existing UI strings — flagged for review.</span>
                </div>
                <button className='ap-rev-resolve' type='button'>
                  Resolve
                </button>
              </div>

              <div className='ap-hist'>
                <div className='ap-hist-row'>
                  <b>v2.1.0</b>
                  <span>Added checkout page translations</span>
                  <i>3f2c41a</i>
                  <button>Restore</button>
                </div>
                <div className='ap-hist-row'>
                  <b>v2.0.0</b>
                  <span>Initial translations</span>
                  <i>9b81d02</i>
                  <button>Restore</button>
                </div>
                <p className='ap-hist-cmd'>
                  $ npx gt translate --tag v2.1.0 -m &ldquo;Added checkout page translations&rdquo;
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
