'use client';

import { useGSAP } from '@gsap/react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useRef } from 'react';

import PrismaticField from '@/components/shared/PrismaticField';

gsap.registerPlugin(useGSAP, ScrollTrigger);

/**
 * The accumulator: sources assembling into a named Context Group, and every
 * later translation drawing from it. The connectors are the brand's doubled
 * thread — two parallel strokes at constant gauge (1.5px stroke, 3px gap),
 * fanning into the group and back out, never merging, never three. The group
 * box itself wears the doubled contour. Scroll draws the threads once;
 * reduced motion gets the finished still.
 *
 * Every value is product-real: the glossary/directive counts match the
 * Signals section above, `v2.1.0 — "Added checkout page translations"` is the
 * CLI's own --tag example, PR #218 is the page family's Locadex PR, and the
 * four consumers are the product's four translation surfaces.
 */

type FlowNode = { name: string; value: string; mark?: string };

const SOURCES: readonly FlowNode[] = [
  { name: 'glossary', value: '12 terms · pinned' },
  { name: 'directives', value: '3 rules · per locale' },
  { name: 'context= tags', value: 'from your code' },
  { name: 'project files', value: 'autogenerated' },
];

const OUTPUTS: readonly FlowNode[] = [
  { name: 'npx gt translate', value: 'build time' },
  { name: 'locadex', value: 'PR #218 · agent', mark: '/brand/no-bg-locadex-logo-light.png' },
  { name: 'tx()', value: 'runtime' },
  { name: 'Translation Editor', value: 'review' },
];

const GROUP_ROWS: readonly (readonly [string, string])[] = [
  ['glossary', '12 terms'],
  ['directives', '3 rules'],
  ['scope', 'organization'],
  ['assigned', '3 projects'],
];

const GROWTH: readonly { at: string; note: string; count: string }[] = [
  { at: 'v1.0.0', note: 'glossary seeded', count: '4 terms' },
  { at: 'v2.0.0', note: 'directives added', count: '9 terms' },
  { at: 'v2.1.0', note: '“Added checkout page translations”', count: '12 terms' },
  { at: 'today', note: 'assigned to 3 projects', count: 'one group' },
];

/* ---- fixed geometry (viewBox units) ---- */
const BOX_W = 240;
const BOX_H = 72;
const SRC_X = 8;
const OUT_X = 856;
const GROUP = { x: 420, y: 112, w: 264, h: 236 } as const;
/* Half of (gauge 1.5 + gap 3): the pair's offset from the path's spine. */
const HALF = 2.25;

/** Row tops for the four flanking nodes. */
const rowTop = (i: number): number => 48 + i * 104;
/** Where the four thread pairs dock on the group's flanks. */
const portY = (i: number): number => 158 + i * 48;

function threadPair(x1: number, y1: number, x2: number, y2: number): readonly [string, string] {
  const mk = (o: number) =>
    `M ${x1} ${y1 + o} C ${x1 + 82} ${y1 + o}, ${x2 - 80} ${y2 + o}, ${x2} ${y2 + o}`;
  return [mk(-HALF), mk(HALF)];
}

export default function GroupBand() {
  const root = useRef<HTMLElement>(null);

  useGSAP(
    () => {
      const scope = root.current;
      if (!scope) return;
      if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

      const threads = gsap.utils.toArray<SVGPathElement>('.ctxb-thread', scope);
      for (const path of threads) {
        const len = path.getTotalLength();
        path.style.strokeDasharray = `${len}`;
        path.style.strokeDashoffset = `${len}`;
      }
      const nodes = gsap.utils.toArray<Element>('.ctxb-node', scope);
      const rows = gsap.utils.toArray<Element>('.ctx-growth > div', scope);

      const tl = gsap.timeline({
        scrollTrigger: { trigger: scope, start: 'top 72%', once: true },
        defaults: { ease: 'power2.out' },
      });
      tl.fromTo(nodes, { autoAlpha: 0, y: 10 }, { autoAlpha: 1, y: 0, duration: 0.5, stagger: 0.05 })
        .to(threads, { strokeDashoffset: 0, duration: 0.85, stagger: 0.04, ease: 'power2.inOut' }, 0.18)
        .fromTo(rows, { autoAlpha: 0, y: 8 }, { autoAlpha: 1, y: 0, duration: 0.45, stagger: 0.06 }, 0.55);
    },
    { scope: root }
  );

  return (
    <section className='tc-band ctx-band' id='groups' ref={root}>
      <PrismaticField
        className='tc-band-field'
        preset='1'
        speed={0.4}
        params={{ exposureScale: 2600 }}
        effects={['lens', 'dither', 'chroma']}
        defaultEffect='lens'
      />

      <div className='tc-band-in'>
        <h2>One group. Every translation.</h2>
        <p className='tc-band-sub'>
          Glossary, directives, and autogenerated project context assemble into a Context Group at the
          organization level. The group grows as the project grows &mdash; and every translation that
          follows draws from it.
        </p>

        <div className='ctx-flow'>
          {/* ---- desktop: the drawn instrument ---- */}
          <svg
            className='ctx-flow-svg'
            viewBox='0 0 1104 460'
            role='img'
            aria-label='Sources — glossary, directives, context tags and project files — flow into one Context Group; build-time translation, Locadex, runtime calls and the Translation Editor all draw out of it'
          >
            {/* column captions */}
            <text className='ctxb-cap' x={SRC_X} y={26}>
              sources
            </text>
            <text className='ctxb-cap' x={OUT_X + BOX_W} y={26} textAnchor='end'>
              every translation draws from it
            </text>

            {/* threads in */}
            {SOURCES.map((source, i) => {
              const [a, b] = threadPair(SRC_X + BOX_W, rowTop(i) + BOX_H / 2, GROUP.x, portY(i));
              return (
                <g key={`in-${source.name}`}>
                  <path className='ctxb-thread' d={a} />
                  <path className='ctxb-thread' d={b} />
                </g>
              );
            })}

            {/* threads out */}
            {OUTPUTS.map((output, i) => {
              const [a, b] = threadPair(GROUP.x + GROUP.w, portY(i), OUT_X, rowTop(i) + BOX_H / 2);
              return (
                <g key={`out-${output.name}`}>
                  <path className='ctxb-thread' d={a} />
                  <path className='ctxb-thread' d={b} />
                </g>
              );
            })}

            {/* source nodes */}
            {SOURCES.map((source, i) => (
              <g className='ctxb-node' key={source.name}>
                <rect className='ctxb-box' x={SRC_X} y={rowTop(i)} width={BOX_W} height={BOX_H} rx={5} />
                <text className='ctxb-name' x={SRC_X + 16} y={rowTop(i) + 30}>
                  {source.name}
                </text>
                <text className='ctxb-val' x={SRC_X + 16} y={rowTop(i) + 50}>
                  {source.value}
                </text>
              </g>
            ))}

            {/* output nodes */}
            {OUTPUTS.map((output, i) => (
              <g className='ctxb-node' key={output.name}>
                <rect className='ctxb-box' x={OUT_X} y={rowTop(i)} width={BOX_W} height={BOX_H} rx={5} />
                {output.mark ? (
                  <image
                    className='ctxb-mark'
                    href={output.mark}
                    x={OUT_X + 16}
                    y={rowTop(i) + 19}
                    width={13}
                    height={13}
                  />
                ) : null}
                <text className='ctxb-name' x={OUT_X + (output.mark ? 35 : 16)} y={rowTop(i) + 30}>
                  {output.name}
                </text>
                <text className='ctxb-val' x={OUT_X + 16} y={rowTop(i) + 50}>
                  {output.value}
                </text>
              </g>
            ))}

            {/* the group: doubled contour at constant gauge */}
            <g className='ctxb-node'>
              <rect
                className='ctxb-group-fill'
                x={GROUP.x}
                y={GROUP.y}
                width={GROUP.w}
                height={GROUP.h}
                rx={6}
              />
              <rect
                className='ctxb-group-line'
                x={GROUP.x}
                y={GROUP.y}
                width={GROUP.w}
                height={GROUP.h}
                rx={6}
              />
              <rect
                className='ctxb-group-line'
                x={GROUP.x + 4.5}
                y={GROUP.y + 4.5}
                width={GROUP.w - 9}
                height={GROUP.h - 9}
                rx={4}
              />
              <text className='ctxb-title' x={GROUP.x + 24} y={GROUP.y + 40}>
                Context Group
              </text>
              <line
                className='ctxb-rule'
                x1={GROUP.x + 24}
                y1={GROUP.y + 56}
                x2={GROUP.x + GROUP.w - 24}
                y2={GROUP.y + 56}
              />
              {GROUP_ROWS.map((row, i) => (
                <g key={row[0]}>
                  <text className='ctxb-key' x={GROUP.x + 24} y={GROUP.y + 88 + i * 32}>
                    {row[0]}
                  </text>
                  <text
                    className='ctxb-name'
                    x={GROUP.x + GROUP.w - 24}
                    y={GROUP.y + 88 + i * 32}
                    textAnchor='end'
                  >
                    {row[1]}
                  </text>
                </g>
              ))}
            </g>
          </svg>

          {/* ---- narrow screens: the same ledger, stacked ---- */}
          <div className='ctx-flow-stack'>
            <div className='ctx-stack-list'>
              {SOURCES.map((source) => (
                <div className='ctx-stack-row' key={source.name}>
                  <b>{source.name}</b>
                  <span>{source.value}</span>
                </div>
              ))}
            </div>
            <div className='ctx-vthread' aria-hidden='true' />
            <div className='ctx-stack-group'>
              <b>Context Group</b>
              {GROUP_ROWS.map((row) => (
                <div className='ctx-stack-row' key={row[0]}>
                  <span>{row[0]}</span>
                  <b>{row[1]}</b>
                </div>
              ))}
            </div>
            <div className='ctx-vthread' aria-hidden='true' />
            <div className='ctx-stack-list'>
              {OUTPUTS.map((output) => (
                <div className='ctx-stack-row' key={output.name}>
                  <b>{output.name}</b>
                  <span>{output.value}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ---- the group over one project's life ---- */}
        <p className='ctx-growth-cap'>the same group, over one project&rsquo;s life</p>
        <div className='ctx-growth'>
          {GROWTH.map((step) => (
            <div key={step.at}>
              <b>{step.at}</b>
              <span>{step.note}</span>
              <em>{step.count}</em>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
