// Unpacks the Ramp demo's dotLottie files from kit/lottie into this film's
// assets, once, at build time, so the render never unzips anything.
//
// A .lottie file is a zip of manifest.json, animations/<id>.json and
// images/*. For each animation and locale this writes
//   assets/<animation>/<locale>.json   the Lottie document, every image
//                                      inlined as a data URI (the blog
//                                      figure's dotlottie.ts does the same)
//   assets/<animation>/<locale>.js     the same document as a script that
//                                      assigns it to window.LTX_DATA, so the
//                                      composition loads it with a plain
//                                      <script> tag and builds every player
//                                      synchronously, before the timeline
//                                      registers (no fetch at render time)
//
// Run from the film folder:  node scripts/unpack.mjs [animation ...]
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const film = join(here, '..');
const kitLottie = join(film, 'kit', 'lottie');
const require = createRequire(import.meta.url);
const { unzipSync, strFromU8 } = require(join(film, 'kit', 'fflate.min.js'));

const MIME = { webp: 'image/webp', png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', svg: 'image/svg+xml' };

function documentOf(file) {
  const files = unzipSync(new Uint8Array(readFileSync(file)));
  const manifest = files['manifest.json'] ? JSON.parse(strFromU8(files['manifest.json'])) : {};
  const id = manifest.animations?.[0]?.id;
  const key =
    id && files[`animations/${id}.json`]
      ? `animations/${id}.json`
      : Object.keys(files).find((k) => k.startsWith('animations/') && k.endsWith('.json'));
  if (!key) throw new Error(`${file}: no animation inside`);
  const doc = JSON.parse(strFromU8(files[key]));
  for (const asset of doc.assets ?? []) {
    if (!asset.p || asset.e === 1 || String(asset.p).startsWith('data:')) continue;
    const joined = `${asset.u ?? ''}${asset.p}`.replace(/^\/+/, '');
    const entry = [joined, `images/${asset.p}`].find((k) => k in files) ?? Object.keys(files).find((k) => k.endsWith(`/${asset.p}`));
    if (!entry) throw new Error(`${file}: image ${asset.p} missing from the zip`);
    const ext = entry.slice(entry.lastIndexOf('.') + 1).toLowerCase();
    asset.p = `data:${MIME[ext] ?? 'application/octet-stream'};base64,${Buffer.from(files[entry]).toString('base64')}`;
    asset.u = '';
    asset.e = 1;
  }
  return doc;
}

const wanted = process.argv.slice(2);
const animations = readdirSync(kitLottie).filter((name) => wanted.length === 0 || wanted.includes(name));
for (const name of animations) {
  const manifest = JSON.parse(readFileSync(join(kitLottie, name, 'manifest.json'), 'utf8'));
  const out = join(film, 'assets', name);
  mkdirSync(out, { recursive: true });
  for (const locale of manifest.locales) {
    const doc = documentOf(join(kitLottie, name, `${locale}.lottie`));
    const json = JSON.stringify(doc);
    writeFileSync(join(out, `${locale}.json`), json);
    writeFileSync(
      join(out, `${locale}.js`),
      `/* generated by scripts/unpack.mjs from kit/lottie/${name}/${locale}.lottie */\n` +
        `(window.LTX_DATA = window.LTX_DATA || {})[${JSON.stringify(`${name}/${locale}`)}] = ${json};\n`
    );
    console.log(`${name}/${locale}: ${doc.w}x${doc.h} ${doc.fr} fps, frames ${doc.ip} to ${doc.op}, ${(json.length / 1024).toFixed(0)} KB`);
  }
}
